# -*- coding: latin-1 -*-
CHAPTER = {
    "number": 21,
    "label": "CHAPTER TWENTY-ONE",
    "title": "DR. SEWARD'S DIARY",
    "subtitle": "12th -- 13th October -- the Asylum",
    "epigraph": '"Come in, Lord and Master!"',
    "docs": [
        {
            "num": "No. I.",
            "title": "THE ACCIDENT IN THE NIGHT.",
            "subtitle": "Dr. Seward's account of the finding of his patient.",
            "style": "prose",
            "paras": [
                "When I came to Renfield's room I found him lying on the floor on his left side in a glittering pool of blood. His face was horribly bruised, as though it had been beaten against the floor; indeed it was from the face wounds that the pool of blood originated. The attendant, Simmons, who was kneeling beside the body, said to me as we turned him over that he thought the poor fellow's back was broken; both the right arm and leg, and the whole side of the face, were paralysed.",
                "How such a thing could have happened puzzled the attendant beyond measure. He could understand the two things separately -- he had seen a patient at Eversfield mark her own face so by beating her head on the floor -- but together they baffled him. 'If his back was broke, he couldn't beat his head; and if his face was like that before the fall out of bed, there would be marks of it.'",
                "I sent at once for Dr. Van Helsing, who came in dressing gown and slippers. After a strict examination we found the wounds of the face superficial; the real injury was a depressed fracture of the skull, extending right up through the motor area. 'We must trephine at once,' said the Professor, 'or it may be too late.' We expected he would recover consciousness after the operation -- for a short time, at all events -- and that his words might be worth many lives.",
            ],
        },
        {
            "num": "No. II.",
            "title": "RENFIELD'S CONFESSION.",
            "subtitle": "Taken down by Dr. Seward from the patient's lips, between life and death.",
            "style": "letter",
            "opening": [
                "Gentlemen, --",
                "I have something that I must say before I die.",
            ],
            "paras": [
                "It was that night after you left me, when I implored you to let me go away. Then there came a sudden peace to me, and my brain seemed to become cool again. He came up to the window in the mist, as I had seen him often before; but he was solid then -- not a ghost, and his eyes were fierce like a man's when angry. He was laughing with his red mouth.",
                "I would not ask him to come in at first, though I knew he wanted to -- just as he had wanted all along. Then he began promising me things -- not in words but by doing them, just as he used to send in the flies when the sun was shining. Then he began to whisper: 'Rats, rats, rats! Hundreds, thousands, millions of them, and every one a life; and dogs to eat them, and cats too. All lives! all red blood, with years of life in it.'",
                "He beckoned me to the window. A dark mass spread over the grass, coming on like the shape of a flame of fire; and then He moved the mist to the right and left, and I could see that there were thousands of rats with their eyes blazing red -- like His, only smaller. And I thought he seemed to be saying: 'All these lives will I give you, ay, and many more and greater, through countless ages, if you will fall down and worship me!' And then a red cloud, like the colour of blood, seemed to close over my eyes; and before I knew what I was doing, I found myself opening the sash and saying to Him: 'Come in, Lord and Master!'",
                "When He came to-night I was ready for Him. I saw the mist stealing in, and I grabbed it tight. I had heard that madmen have unnatural strength; and as I knew I was a madman -- at times anyhow -- I resolved to use my power. I held tight; and I thought I was going to win, for I didn't mean Him to take any more of her life, till I saw His eyes. They burned into me, and my strength became like water. He raised me up and flung me down. There was a red cloud before me, and a noise like thunder, and the mist seemed to steal away under the door.",
                "Quick, Doctor, quick. I am dying! Wet my lips with brandy again. I must not deceive myself; it was no dream, but all a grim reality. Tell them -- tell them I tried to bar the way.",
            ],
            "signoff": "-- Spoken to the last,",
            "signature": "R. M. RENFIELD.",
        },
        {
            "num": "No. III.",
            "title": "NOTICE TO THE STAFF.",
            "subtitle": "Posted in the attendants' room by order of the Medical Superintendent.",
            "style": "notice",
            "lead": "THE WEST WING IS TO BE KEPT QUIET.",
            "paras": [
                "The attendant's round is to be doubled until further notice, and no visitor is to be admitted to the west wing after nightfall.",
                "Any unusual sound, in any quarter, is to be reported instantly to Dr. Seward himself, and not to be discussed in the servants' hall.",
                "The Medical Superintendent regrets that, in the present state of his knowledge, he is unable to say with confidence what is to be regarded as usual.",
            ],
        },
        {
            "num": "No. IV.",
            "title": "MIDNIGHT IN THE HARKERS' ROOM.",
            "subtitle": "What was found when the door was burst open.",
            "style": "prose",
            "paras": [
                "We knew the worst now: He was here, and we knew His purpose. We armed ourselves as we had when we entered the Count's house, and hurried to the Harkers' door. The door did not yield; we threw ourselves against it, and with a crash it burst open.",
                "On the bed beside the window lay Jonathan Harker, his face flushed and breathing heavily as though in a stupor. Kneeling on the near edge of the bed was the white-clad figure of his wife; and by her side stood a tall, thin man, clad in black. His left hand held both Mrs. Harker's hands, keeping them away with her arms at full tension; his right hand gripped her by the back of the neck, forcing her face down on his bosom. Her white nightdress was smeared with blood.",
                "As we burst into the room the Count turned his face, and the hellish look seemed to leap into it. With a wrench he turned and sprang at us; but by this time the Professor had gained his feet, and was holding towards him the envelope which contained the Sacred Wafer. The Count suddenly stopped, just as poor Lucy had done outside the tomb, and cowered back. Further and further back he cowered, as we, lifting our crucifixes, advanced.",
                "The moonlight suddenly failed, as a great black cloud sailed across the sky; and when the gaslight sprang up under Quincey's match, we saw nothing but a faint vapour. This, as we looked, trailed under the door. Quincey had run across the lawn and hidden in the shadow of a great yew-tree; he told us afterwards that he saw a bat rise from Renfield's window, and flap westward. The Count will not be back to-night; for the sky was reddening in the east, and the dawn was close.",
                "Arthur looked into Renfield's room on his way back from the study, where all the manuscript had been burned and the blue flames were flickering amongst the white ashes. There was no trace there -- except that the poor fellow is dead. Mrs. Harker raised her head and said solemnly: 'God's will be done!'",
            ],
        },
        {
            "num": "No. V.",
            "title": "MRS. HARKER'S DECLARATION.",
            "subtitle": "Dictated to her husband, in the night of the 12th.",
            "style": "letter",
            "opening": [
                "My dearest Jonathan, --",
                "You must let me set down what happened, while I can bear to speak of it.",
            ],
            "paras": [
                "There was in the room the same thin white mist that I had before noticed, and the same sense of some presence. Beside the bed, as if the mist had turned into his figure, for it had entirely disappeared, stood a tall, thin man, all in black. I knew him at once from the description of the others -- the waxen face, the high aquiline nose, the parted red lips, and the red eyes that I had seemed to see in the sunset on the windows of St. Mary's Church at Whitby. I knew, too, the red scar on his forehead where you had struck him.",
                "In the pause he spoke in a sort of keen, cutting whisper, pointing as he spoke to you: 'Silence! If you make a sound I shall take him and dash his brains out before your very eyes.' With a mocking smile, he placed one hand upon my shoulder and, holding me tight, bared my throat with the other, saying as he did so, 'First, a little refreshment to reward my exertions. You may as well be quiet; it is not the first time, or the second, that your veins have appeased my thirst!'",
                "Then he spoke to me mockingly: 'And so you, like the others, would play your brains against mine. Whilst they played wits against me -- against me who commanded nations, and intrigued for them, and fought for them, hundreds of years before they were born -- I was countermining them. And you, their best beloved one, are now to me, flesh of my flesh; blood of my blood; kin of my kin; my bountiful wine-press for a while; and shall be later on my companion and my helper.'",
                "Unclean, unclean! I must touch him or kiss him no more. Oh, that it should be that it is I who am now his worst enemy, and whom he may have most cause to fear.",
            ],
            "signoff": "-- Your broken-hearted",
            "signature": "MINA.",
        },
        {
            "num": "No. VI.",
            "title": "THE MARK OF THE WAFER.",
            "subtitle": "The morning after; in the presence of them all.",
            "style": "prose",
            "paras": [
                "Before we went forth to our terrible enterprise, Van Helsing would see Madam Mina armed against personal attack. 'On your forehead I touch this piece of Sacred Wafer in the name of the Father, the Son, and --' There was a fearful scream which almost froze our hearts to hear. As he had placed the Wafer on Mina's forehead, it had seared it -- had burned into the flesh as though it had been a piece of white-hot metal.",
                "She sank on her knees on the floor in an agony of abasement, pulling her beautiful hair over her face, as the leper of old his mantle, and wailed out: 'Unclean! Unclean! Even the Almighty shuns my polluted flesh! I must bear this mark of shame upon my forehead until the Judgment Day.'",
                "Then Van Helsing turned and said gravely, so gravely that I could not help feeling that he was in some way inspired: 'It may be that you may have to bear that mark till God himself see fit, as He most surely shall, on the Judgment Day, to redress all wrongs of the earth. And oh, Madam Mina, my dear, my dear, may we who love you be there to see, when that red scar, the sign of God's knowledge of what has been, shall pass away, and leave your forehead as pure as the heart we know.'",
                "There was hope in his words, and comfort; and they made for resignation. Then without a word we all knelt down together, and, all holding hands, swore to be true to each other. We men pledged ourselves to raise the veil of sorrow from the head of her whom, each in his own way, we loved.",
            ],
        },
        {
            "num": "No. VII.",
            "title": "UNDERTAKER'S ACCOUNT.",
            "subtitle": "Rendered to Dr. Seward, and paid.",
            "style": "bill",
            "bill_title": "MESSRS. ----, UNDERTAKERS.",
            "bill_sub": "Funeral of Mr. R. M. Renfield -- 13th October.",
            "items": [
                ("Elm coffin, best, with fittings", "1 10 0"),
                ("Shroud, fine linen", "0 7 6"),
                ("Attendance through the night", "0 10 0"),
                ("Carriage to the cemetery and back", "0 15 0"),
                ("Medical certificate; death by misadventure", "--"),
            ],
            "total": "TOTAL ............ 2 12 6 -- paid with thanks.",
            "note": "(The deceased was much liked by the attendants, who subscribed among themselves for a wreath. The Doctor paid the account himself, and asked that the grave be kept neat.)",
        },
    ],
    "plates": [
        {
            "after_doc": 6,
            "file": "plates/funeral.jpg",
            "numeral": "Plate III.",
            "title": "THE LAST OF RENFIELD.",
            "caption": "A plain elm coffin, a quiet grave; he died trying to bar the way.",
            "prompt": "19th century oil painting, vertical portrait composition: a small Victorian cemetery at dawn, a plain elm coffin being lowered into a grave, four mourners standing bareheaded, the high walls of a lunatic asylum visible behind bare trees, pale morning light. Quiet and dignified, Victorian book-illustration style. No text, no watermark.",
        },
        {
            "after_doc": 2,
            "file": "plates/cell.jpg",
            "numeral": "Plate I.",
            "title": "THE EMPTY CELL.",
            "caption": "Renfield's cell after the struggle -- the chair overturned, the lantern still burning.",
            "prompt": "19th century oil painting, vertical portrait composition: a sparse Victorian lunatic asylum cell at night, an iron bedstead with rumpled sheets, an overturned wooden chair, a barred window with moonlight streaming in, an attendant's lantern left burning on the floor. Empty and still, aftermath of a struggle, Victorian book-illustration style. No text, no watermark.",
        },
        {
            "after_doc": 4,
            "file": "plates/wafer.jpg",
            "numeral": "Plate II.",
            "title": "THE WAFER.",
            "caption": "The sacred wafer, held to the light -- that which seared, and that which may yet save.",
            "prompt": "19th century oil painting, vertical portrait composition: a distinguished elderly professor with a white beard in a quiet chapel, holding a small white communion wafer up toward a shaft of morning light from a stained-glass window, his expression grave and tender, wooden pews around him. Solemn and reverent, Victorian book-illustration style. No text, no watermark.",
        },
    ],
}
