# -*- coding: latin-1 -*-
CHAPTER = {
    "number": 6,
    "label": "CHAPTER SIX",
    "title": "MINA MURRAY'S JOURNAL",
    "subtitle": "24th July -- 6th August -- Whitby",
    "epigraph": '"It be all fool-talk, lock, stock, and barrel; that\'s what it be, an\' nowt else."',
    "docs": [
        {
            "num": "No. I.",
            "title": "OF WHITBY TOWN.",
            "subtitle": "From Mina Murray's Journal, 24th July.",
            "style": "prose",
            "paras": [
                "Lucy met me at the station, looking sweeter and lovelier than ever, and we drove up to the house at the Crescent in which they have rooms. This is a lovely place. The little river, the Esk, runs through a deep valley, which broadens out as it comes near the harbour. A great viaduct runs across, with high piers, through which the view seems somehow further away than it really is.",
                "The houses of the old town are all red-roofed, and seem piled up one over the other anyhow, like the pictures we see of Nuremberg. Right over the town is the ruin of Whitby Abbey, which was sacked by the Danes, and which is the scene of part of \"Marmion,\" where the girl was built up in the wall. Between it and the town there is another church, the parish one, round which is a big graveyard, all full of tombstones.",
                "This is to my mind the nicest spot in Whitby, for it lies right over the town, and has a full view of the harbour and all up the bay to where the headland called Kettleness stretches out into the sea. It descends so steeply over the harbour that part of the bank has fallen away, and some of the graves have been destroyed. There are walks, with seats beside them, through the churchyard; and people go and sit there all day long looking at the beautiful view and enjoying the breeze.",
                "Outside the harbour there rises for about half a mile a great reef, at the end of which is a buoy with a bell, which swings in bad weather, and sends in a mournful sound on the wind. They have a legend here that when a ship is lost bells are heard out at sea. I am writing now, with my book on my knee, and listening to the talk of three old men who are sitting beside me. They seem to do nothing all day but sit up here and talk.",
            ],
        },
        {
            "num": "No. II.",
            "title": "MR. SWALES'S SERMON.",
            "subtitle": "From Mina Murray's Journal, 1st August; taken down from the churchyard seat.",
            "style": "prose",
            "paras": [
                "He is a funny old man. He must be awfully old, for his face is all gnarled and twisted like the bark of a tree. He tells me that he is nearly a hundred, and that he was a sailor in the Greenland fishing fleet when Waterloo was fought. I got him on the subject of the legends, and he went off at once into a sort of sermon. I must try to remember it and put it down:--",
                "\"It be all fool-talk, lock, stock, and barrel; that's what it be, an' nowt else. These bans an' wafts an' boh-ghosts an' barguests an' bogles an' all anent them is only fit to set bairns an' dizzy women a-belderin'. They be nowt but air-blebs. They, an' all grims an' signs an' warnin's, be all invented by parsons an' illsome beuk-bodies an' railway touters to skeer an' scunner hafflin's.\"",
                "And then of the tombstones: \"Look here all around you in what airt ye will; all them steans, holdin' up their heads as well as they can out of their pride, is acant -- simply tumblin' down with the weight o' the lies wrote on them, 'Here lies the body' or 'Sacred to the memory' wrote on all of them, an' yet in nigh half of them there bean't no bodies at all; an' the memories of them bean't cared a pinch of snuff about, much less sacred. Lies all of them, nothin' but lies of one kind or another!\"",
                "I went over and read one of them: \"Edward Spencelagh, master mariner, murdered by pirates off the coast of Andres, April, 1854, aet. 30.\" \"Who brought him home, I wonder, to hap him here?\" says Mr. Swales. \"Murdered off the coast of Andres! an' you consated his body lay under! Why, I could name ye a dozen whose bones lie in the Greenland seas above -- or where the currents may have drifted them.\"",
                "He pointed to a stone at our feet which had been laid down as a slab, on which the seat was rested, close to the edge of the cliff. Lucy leant over and read: \"Sacred to the memory of George Canon, who died, in the hope of a glorious resurrection, on July, 29, 1873, falling from the rocks at Kettleness.\" \"Really, Mr. Swales, I don't see anything very funny in that!\" said Lucy, very gravely.",
                "\"Ye don't see aught funny! Ha! ha! But that's because ye don't gawm the sorrowin' mother was a hell-cat that hated him because he was acrewk'd -- a regular lamiter he was -- an' he hated her so that he committed suicide in order that she mightn't get an insurance she put on his life. He blew nigh the top of his head off with an old musket that they had for scarin' the crows with. An', as to hopes of a glorious resurrection, I've often heard him say masel' that he hoped he'd go to hell, for his mother was so pious that she'd be sure to go to heaven, an' he didn't want to addle where she was.\"",
                "Lucy turned the conversation, rising up: \"Oh, why did you tell us of this? It is my favourite seat, and I cannot leave it; and now I find I must go on sitting over the grave of a suicide.\" \"That won't harm ye, my pretty; an' it may make poor Geordie gladsome to have so trim a lass sittin' on his lap.\"",
            ],
        },
        {
            "num": "No. III.",
            "title": "A LINE FROM EXETER.",
            "subtitle": "Hawkins & Hawkins, Solicitors, Exeter, to Miss Mina Murray.",
            "style": "letter",
            "opening": [
                "The Albany, Exeter.",
                "25th July, 1893.",
                "My dear Miss Murray, --",
            ],
            "paras": [
                "I have great pleasure in enclosing a letter which has just reached me, addressed in the hand of your friend Mr. Jonathan Harker. It is but a single line, dated from Castle Dracula, and says only that he is just starting for home; but I thought you would wish to see it without an hour's delay, and to have the comfort of his own writing under your eye.",
                "You will, I hope, forgive the terseness of the communication; the young gentleman is no doubt much pressed by the business which detained him, and which, I am given to understand, is now happily completed. We shall expect him in England very shortly.",
                "Mrs. Hawkins joins me in kind regards, and in the hope that you and Miss Westenra are enjoying the sea air at Whitby to the full.",
            ],
            "signoff": "I remain, dear Miss Murray,",
            "signature": "PETER HAWKINS.",
        },
        {
            "num": "No. IV.",
            "title": "THE STRANGE SHIP.",
            "subtitle": "From Mina Murray's Journal, 6th August.",
            "style": "prose",
            "paras": [
                "To-day is a grey day, and everything is grey -- except the green grass, which seems like emerald amongst it. The sea is tumbling in over the shallows with a roar, muffled in the sea-mists drifting inland. Dark figures are on the beach here and there, and seem \"men like trees walking.\" The fishing-boats are racing for home, bending to the scuppers. The fishermen say that we are in for a storm.",
                "Here comes old Mr. Swales, making straight for me. I have been quite touched by the change in the poor old man. When he sat down beside me, he said in a very gentle way: \"I'm afraid, my deary, that I must have shocked you by all the wicked things I've been sayin' about the dead, and such like, for weeks past; but I didn't mean them, and I want ye to remember that when I'm gone.\"",
                "\"My time must be nigh at hand now, for I be aud, and a hundred years is too much for any man to expect; and I'm so nigh it that the Aud Man is already whettin' his scythe. But don't ye dooal an' greet, my deary!\" -- for he saw that I was crying -- \"if he should come this very night I'd not refuse to answer his call. For life be, after all, only a waitin' for somethin' else than what we're doin'; and death be all that we can rightly depend on.\"",
                "Then he cried suddenly: \"Look! look! There's something in that wind and in the hoast beyont that sounds, and looks, and tastes, and smells like death. It's in the air; I feel it comin'. Lord, make me answer cheerful when my call comes!\" He held up his arms devoutly, and raised his hat. His mouth moved as though he were praying. Then he shook hands with me, and blessed me, and said good-bye, and hobbled off. It all touched me, and upset me very much.",
                "I was glad when the coastguard came along, with his spy-glass under his arm. He stopped to talk with me, as he always does, but all the time kept looking at a strange ship. \"I can't make her out,\" he said; \"she's a Russian, by the look of her; but she's knocking about in the queerest way. She doesn't know her mind a bit; she seems to see the storm coming, but can't decide whether to run up north in the open, or to put in here.\"",
                "\"Look there again! She is steered mighty strangely, for she doesn't mind the hand on the wheel; changes about with every puff of wind. We'll hear more of her before this time to-morrow.\"",
            ],
        },
        {
            "num": "No. V.",
            "title": "THE ZOOPHAGOUS PATIENT.",
            "subtitle": "From Dr. Seward's Diary, 5th June -- 20th July; kept at the asylum.",
            "style": "prose",
            "paras": [
                "The case of Renfield grows more interesting the more I get to understand the man. He has certain qualities very largely developed; selfishness, secrecy, and purpose. His redeeming quality is a love of animals, though, indeed, he has such curious turns in it that I sometimes imagine he is only abnormally cruel. His pets are of odd sorts. Just now his hobby is catching flies. He has at present such a quantity that I have had myself to expostulate.",
                "On the 18th of June he had turned his mind to spiders, and had got several very big fellows in a box. He keeps feeding them with his flies, and the number of the latter is becoming sensibly diminished. By the 8th of July he had managed to get a sparrow, and had already partially tamed it. His means of taming is simple, for already the spiders have diminished. Those that do remain, however, are well fed, for he still brings in the flies by tempting them with his food.",
                "By the 19th he had a whole colony of sparrows, and his flies and spiders were almost obliterated; and he came fawning to me like a dog to ask a very, very great favour: \"A kitten, a nice little, sleek playful kitten, that I can play with, and teach, and feed -- and feed -- and feed!\" I said I would see about it. His face fell, and I could see a warning of danger in it, for there was a sudden fierce, sidelong look which meant killing. The man is an undeveloped homicidal maniac.",
                "He keeps a little note-book in which he is always jotting down something. Whole pages of it are filled with masses of figures, generally single numbers added up in batches, and then the totals added in batches again, as though he were \"focussing\" some account, as the auditors put it. And once, when a horrid blow-fly, bloated with some carrion food, buzzed into the room, he caught it, held it exultantly for a few moments between his finger and thumb, and put it in his mouth and ate it. He argued quietly that it was very good and very wholesome; that it was life, strong life, and gave life to him.",
                "On the 20th I visited him very early and found him up and humming a tune, spreading out his sugar in the window, manifestly beginning his fly-catching again. I looked around for his birds, and not seeing them, asked him where they were. He replied, without turning round, that they had all flown away. There were a few feathers about the room and on his pillow a drop of blood. Later the attendant reported that Renfield had been very sick and had disgorged a whole lot of feathers. \"My belief is, doctor,\" he said, \"that he has eaten his birds, and that he just took and ate them raw!\"",
                "The thought that has been buzzing about my brain lately is complete, and the theory proved. My homicidal maniac is of a peculiar kind. I shall have to invent a new classification for him, and call him a zoophagous (life-eating) maniac; what he desires is to absorb as many lives as he can, and he has laid himself out to achieve it in a cumulative way. He gave many flies to one spider and many spiders to one bird, and then wanted a cat to eat the many birds. What would have been his later steps? It would almost be worth while to complete the experiment.",
            ],
        },
        {
            "num": "No. VI.",
            "title": "THE ANGEL OF DEATH.",
            "subtitle": "Old Mr. Swales's farewell, spoken on the cliff, 6th August.",
            "style": "broadside",
            "paras": [
                "For life be, after all,",
                "only a waitin' for somethin' else",
                "than what we're doin';",
                "and death be all",
                "that we can rightly depend on.",
                "But I'm content,",
                "for it's comin' to me, my deary,",
                "and comin' quick.",
            ],
        },
    ],
    "plates": [
        {
            "after_doc": 1,
            "file": "plates/whitby.jpg",
            "numeral": "Plate I.",
            "title": "THE CHURCHYARD ON THE CLIFF.",
            "caption": "The abbey ruins above the harbour; two young ladies on the seat among the tombstones, with their old oracle of the churchyard.",
            "prompt": "19th century oil painting, vertical portrait composition: the ruins of a great Gothic abbey on a clifftop above a harbour town, an old churchyard crowded with leaning tombstones overlooking the sea at sunset, two young Victorian women in summer dresses seated on a stone bench, an ancient weathered sailor with a stick talking to them. Deeply atmospheric, Victorian book-illustration style. No text, no watermark.",
        },
        {
            "after_doc": 3,
            "file": "plates/russian-ship.jpg",
            "numeral": "Plate II.",
            "title": "THE STRANGE SHIP.",
            "caption": "A Russian schooner, steered mighty strangely, knocking about off Kettleness in the coming storm.",
            "prompt": "19th century oil painting, vertical portrait composition: a dark Russian sailing schooner with all sails set tossed on a grey stormy sea off a rocky headland, black clouds piling overhead, no living soul visible on deck, an eerie sense of abandonment, seen from a clifftop. Deeply atmospheric, Victorian book-illustration style. No text, no watermark.",
        },
        {
            "after_doc": 5,
            "file": "plates/swales.jpg",
            "numeral": "Plate III.",
            "title": "MR. SWALES'S FAREWELL.",
            "caption": "\"Lord, make me answer cheerful when my call comes!\" -- the old man blesses Miss Murray and hobbles home.",
            "prompt": "19th century oil painting, vertical portrait composition: an ancient gnarled sailor nearly a hundred years old, face twisted like bark, raising his hat in blessing toward a storm-dark sea on a clifftop path, a young woman in Victorian dress holding his wrinkled hand, wind blowing, distant abbey ruins. Deeply atmospheric, Victorian book-illustration style. No text, no watermark.",
        },
    ],
}
