# -*- coding: latin-1 -*-
"""Chapter 25 content for the Dracula companion."""
CHAPTER = {
    "number": 25,
    "label": "CHAPTER TWENTY-FIVE",
    "title": "DR. SEWARD'S DIARY",
    "subtitle": "11th -- 28th October",
    "epigraph": '"This is what I can give into the hotch-pot."',
    "docs": [
        {
            "num": "No. I.",
            "title": "THE OATH.",
            "subtitle": "Exacted by Mrs. Harker, before sunset, 11th October.",
            "style": "notice",
            "lead": "YOU MUST PROMISE ME, ONE AND ALL -- THAT YOU WILL KILL ME.",
            "paras": [
                '"When you shall be convinced that I am so changed that it is better that I die than I may live. When I am thus dead in the flesh, then you will, without a moment\'s delay, drive a stake through me and cut off my head."',
                "Mr. Morris was the first to rise. He knelt down before her and said solemnly: 'Should the time ever come, I shall not flinch from the duty that you have set us.' Dr. Van Helsing swore the same, and Lord Godalming, and Dr. Seward; and her husband last, wan-eyed, with a greenish pallor which subdued the snowy whiteness of his hair.",
                '"And now one word of warning, a warning which you must never forget: this time, if it ever come, may come quickly and unexpectedly. At such a time I myself might be -- nay! if the time ever comes, shall be -- leagued with your enemy against you."',
                "Then her husband read the Burial Service over her, in tones so broken with emotion that often he had to pause.",
            ],
        },
        {
            "num": "No. II.",
            "title": "TELEGRAM.",
            "subtitle": "The first news of the ship.",
            "style": "telegram",
            "tfrom": "Rufus Smith, Lloyd's, London",
            "tto": "Lord Godalming, care of H. B. M. Vice-Consul, Varna",
            "tdated": "24th October",
            "body": "Czarina Catherine reported this morning from Dardanelles STOP",
        },
        {
            "num": "No. III.",
            "title": "A WEEK OF WAITING.",
            "subtitle": "Varna, 15th -- 24th October.",
            "style": "prose",
            "paras": [
                "We left Charing Cross on the morning of the 12th, got to Paris the same night, and took the places secured for us in the Orient Express. We travelled night and day, arriving here at about five o'clock. The rest of us came on to this hotel -- 'the Odessus.' Until the Czarina Catherine comes into port there will be no interest for me in anything in the wide world.",
                "Lord Godalming had four telegrams, one each day since we started, and all to the same effect: that the Czarina Catherine had not been reported to Lloyd's from anywhere. He was to have a message even if she were not reported, so that he might be sure that there was a watch being kept at the other end of the wire.",
                "At sunrise and sunset it has become a habit for Van Helsing to hypnotise Mrs. Harker. He always asks her what she can see and hear. She answers to the first: 'Nothing; all is dark.' And to the second: 'I can hear the waves lapping against the ship, and the water rushing by. Canvas and cordage strain and masts and yards creak. The wind is high -- I can hear it in the shrouds, and the bow throws back the foam.' It is evident that the Czarina Catherine is still at sea, hastening on her way to Varna.",
                "'Thank God! this is the country where bribery can do anything, and we are well supplied with money. We have only to make sure that the ship cannot come into port between sunset and sunrise without our being warned, and we shall be safe. Judge Moneybag will settle this case, I think!'",
                "An hour ago I found Mr. Harker whetting the edge of the great Ghoorka knife which he now always carries with him. It will be a bad lookout for the Count if the edge of that 'Kukri' ever touches his throat, driven by that stern, ice-cold hand!",
            ],
        },
        {
            "num": "No. IV.",
            "title": "HOTEL ODESSUS, VARNA.",
            "subtitle": "Account of the English party, 15th -- 28th October.",
            "style": "bill",
            "bill_title": "HOTEL ODESSUS, VARNA.",
            "bill_sub": "Account of the English party, 15th -- 28th October.",
            "items": [
                ("Rooms for six, thirteen nights", "--"),
                ("Dinners, taken early, that all might retire", "--"),
                ("Telegrams to and from Lloyd's, daily", "--"),
                ("Special messenger to the harbour, to stand watch", "--"),
                ("Gratuities to officials, that the ship be reported the instant she is seen", "--"),
            ],
            "total": "TOTAL ............ to be settled by Lord Godalming.",
            "note": "(Mrs. Harker's colour is coming back; she sleeps a great deal, and throughout the journey slept nearly all the time.)",
        },
        {
            "num": "No. V.",
            "title": "TELEGRAM.",
            "subtitle": "The bolt falls.",
            "style": "telegram",
            "tfrom": "Rufus Smith, Lloyd's, London",
            "tto": "Lord Godalming, care of H. B. M. Vice-Consul, Varna",
            "tdated": "28th October",
            "body": "Czarina Catherine reported entering Galatz at one o'clock to-day STOP",
        },
        {
            "num": "No. VI.",
            "title": "OF THE CRIMINAL TYPE.",
            "subtitle": "From the council of 28th October.",
            "style": "prose",
            "paras": [
                "'Have you ever study the philosophy of crime? There is this peculiarity in criminals. It is so constant, in all countries and at all times, that even police, who know not much from philosophy, come to know it empirically. The criminal always work at one crime -- that is the true criminal who seems predestinate to crime, and who will of none other. This criminal has not full man-brain. He is clever and cunning and resourceful; but he be not of man-stature as to brain. He be of child-brain in much.'",
                "'The Count is a criminal and of criminal type. Nordau and Lombroso would so classify him, and as criminal he is of imperfectly formed mind. Thus, in a difficulty he has to seek resource in habit. His past is a clue, and the one page of it that we know -- and that from his own lips -- tells that once before, when in what Mr. Morris would call a \"tight place,\" he went back to his own country from the land he had tried to invade, and thence, without losing purpose, prepared himself for a new effort.'",
                "'So he came to London to invade a new land. He was beaten, and when all hope of success was lost, and his existence in danger, he fled back over the sea to his home; just as formerly he had fled back over the Danube from Turkey Land.'",
                "The Professor took her hand, his finger and thumb closing on her pulse. 'Seventy-two only; and in all this excitement. I have hope.'",
            ],
        },
    ],
    "plates": [
        {
            "after_doc": 0,
            "file": "plates/oath.jpg",
            "numeral": "Plate I.",
            "title": "THE OATH.",
            "caption": "Quincey was the first to rise after the pause. He knelt down before her.",
            "prompt": "19th century oil painting, vertical portrait composition: a pale young Victorian woman half-reclining on a sofa at sunset in a lamplit room, a rugged frontiersman kneeling before her kissing her hand while four grave Victorian gentlemen stand watching, heavy solemn mood. Deeply atmospheric, Victorian book-illustration style. No text, no watermark.",
        },
        {
            "after_doc": 2,
            "file": "plates/trance.jpg",
            "numeral": "Plate II.",
            "title": "THE HYPNOTIC REPORT.",
            "caption": "'Nothing; all is dark.... I can hear the waves lapping against the ship.'",
            "prompt": "19th century oil painting, vertical portrait composition: a young woman lying entranced on a sofa in a dim hotel room, an elderly white-bearded professor leaning over her with one hand raised, anxious Victorian gentlemen watching, the moonlit Black Sea visible through a tall window. Deeply atmospheric, Victorian book-illustration style. No text, no watermark.",
        },
        {
            "after_doc": 4,
            "file": "plates/kukri.jpg",
            "numeral": "Plate III.",
            "title": "THE KUKRI.",
            "caption": "An hour ago I found him whetting the edge of the great Ghoorka knife.",
            "prompt": "19th century oil painting, vertical portrait composition: a gaunt hollow-eyed young Victorian man in a sparse hotel bedroom whetting a great curved Ghoorka knife on a stone, cold grey morning light through the window, grim resolve. Deeply atmospheric, Victorian book-illustration style. No text, no watermark.",
        },
    ],
}
