# -*- coding: latin-1 -*-
CHAPTER = {
    "number": 22,
    "label": "CHAPTER TWENTY-TWO",
    "title": "JONATHAN HARKER'S JOURNAL",
    "subtitle": "13th -- 14th October -- the pursuit is resolved",
    "epigraph": '"The lapping of water. It is gurgling by, and little waves leap."',
    "docs": [
        {
            "num": "No. I.",
            "title": "THE TRANCE AT DAWN.",
            "subtitle": "Before sunrise, in Mrs. Harker's chamber.",
            "style": "prose",
            "paras": [
                "Mina woke me before the dawn with an idea that must have come in the night, and matured without her knowing it. 'I want you to hypnotise me!' she said to the Professor. 'Do it before the dawn, for I feel that then I can speak, and speak freely. Be quick, for the time is short!'",
                "Van Helsing motioned her to sit up in bed, and looking fixedly at her, commenced to make passes in front of her, from over the top of her head downward, with each hand in turn. Gradually her eyes closed, and she sat stock still; only by the gentle heaving of her bosom could one know that she was alive. Then Mina opened her eyes; but she did not seem the same woman. There was a far-away look in her eyes, and her voice had a sad dreaminess which was new to me.",
                "'Where are you?' The answer came in a neutral way: 'I do not know. Sleep has no place it can call its own.' 'What do you see?' 'I can see nothing; it is all dark.' 'What do you hear?' 'The lapping of water. It is gurgling by, and little waves leap. I can hear them on the outside.' 'Then you are on a ship?' 'Oh, yes!' 'What else do you hear?' 'The sound of men stamping overhead as they run about. There is the creaking of a chain, and the loud tinkle as the check of the capstan falls into the rachet.' 'What are you doing?' 'I am still -- oh, so still. It is like death!'",
                "The voice faded away into a deep breath as of one sleeping, and the open eyes closed again. When she woke she asked only: 'Have I been talking in my sleep?' She seemed, however, to know the situation without telling, though she was eager to know what she had told.",
            ],
        },
        {
            "num": "No. II.",
            "title": "THE TRANCE AT SUNSET.",
            "subtitle": "The evening sitting; the answer unvaried.",
            "style": "prose",
            "paras": [
                "At sunset she was hypnotised again, and once more the Professor put his questions in the low level tone which would not break the current of her thoughts. The answers came dreamily, but with intention, as though she were interpreting something she heard far away.",
                "Lapping waves, and rushing water; darkness, and favouring winds. The creaking of masts, and the sound of men stamping overhead. Stillness -- oh, so still. It is like death.",
                "Morning and evening the report is the same, and the Professor's face grows grimmer with every sitting. He says that so long as the answers do not change, we know the Count is still upon the sea, with the fog at his command, hurrying to his destination. To his doom, we trust.",
            ],
        },
        {
            "num": "No. III.",
            "title": "TELEGRAM.",
            "subtitle": "Lord Godalming's preparations, before the search of Piccadilly.",
            "style": "telegram",
            "tfrom": "Lord Godalming, London",
            "tto": "His Agent, Exeter",
            "tdated": "13th October",
            "body": "Have horses and carriages ready where most convenient STOP May require them at short notice in Walworth Mile End or Piccadilly STOP Engage also two closed cabs for the eastward districts STOP Say nothing to any one STOP",
        },
        {
            "num": "No. IV.",
            "title": "AT LLOYD'S.",
            "subtitle": "Dr. Van Helsing's account of the search for the ship.",
            "style": "prose",
            "paras": [
                "As I knew that he wanted to get back to Transylvania, I felt sure that he must go by the Danube mouth, or by somewhere in the Black Sea, since by that way he come. We start to find what ships leave for the Black Sea. He was in a sailing ship, since Madam Mina tell of sails being set; these not so important as to go in your list of the shipping in the Times.",
                "And so we go, by suggestion of Lord Godalming, to your Lloyd's, where are note of all ships that sail, however so small. There we find that only one Black-Sea-bound ship go out with the tide. She is the Czarina Catherine, and she sail from Doolittle's Wharf for Varna, and thence on to other parts and up the Danube. 'Soh!' said I, 'this is the ship whereon is the Count.'",
                "We have the best proof of that: your own evidence, when in the hypnotic trance this morning. The lapping of water, the stamping of men overhead, the creaking chain -- it is the weighing of the anchor that she heard, whilst she spoke.",
            ],
        },
        {
            "num": "No. V.",
            "title": "THE MAN IN THE STRAW HAT.",
            "subtitle": "What the men at Doolittle's Wharf told us, for a consideration.",
            "style": "prose",
            "paras": [
                "They make known to us how last afternoon at about five o'clock comes a man so hurry. A tall man, thin and pale, with high nose and teeth so white, and eyes that seem to be burning. That he be all in black, except that he have a hat of straw which suit not him or the time. That he scatter his money in making quick inquiry as to what ship sails for the Black Sea and for where.",
                "Some took him to the office and then to the ship, where he will not go aboard but halt at shore end of gang-plank, and ask that the captain come to him. The captain agree to terms. Then the thin man go and soon he come again, himself driving cart on which a great box; this he himself lift down, though it take several to put it on truck for the ship. He give much talk to the captain as to how and where his box is to be placed.",
                "No sooner was all settled than a thin mist began to creep up from the river, and it grew, and grew; till soon a dense fog enveloped the ship and all around her. The captain swore polyglot -- very polyglot -- but he could do nothing. And when the fog begin to melt away, and all was clear again, the thin man was gone; none had seen him come off. The ship went out on the ebb tide; and was doubtless by morning far down the river mouth.",
            ],
        },
        {
            "num": "No. VI.",
            "title": "EXPECTED PASSAGE OF THE CZARINA CATHERINE.",
            "subtitle": "Compiled from the master's best information; all reports to be wired instantly.",
            "style": "timetable",
            "rows": [
                ("Doolittle's Wharf, London", "sailed", "with the ebb tide"),
                ("The Nore", "passed", "--"),
                ("Dover, the Strait", "passed", "--"),
                ("The Dardanelles", "to be reported", "by wire"),
                ("Varna, Black Sea", "expected", "in due course"),
            ],
            "note": "As she must pass the Dardanelles we are sure to have some report. Any person sighting a barque answering her description is entreated to telegraph at once to Lord Godalming, London.",
            "paras": [
                "To sail a ship takes time, go she never so quick; and when we start we go on land more quick, and we meet him there. Our best hope is to come on him when in the box between sunrise and sunset; for then he can make no struggle, and we may deal with him as we should.",
            ],
        },
        {
            "num": "No. VII.",
            "title": "VAN HELSING TO HARKER.",
            "subtitle": "Message left on the phonograph, before the search.",
            "style": "letter",
            "opening": [
                "My dear friend Jonathan, --",
                "You are to stay with your dear Madam Mina. This is your best and most holiest office.",
            ],
            "paras": [
                "We shall go to make our search -- if I can call it so, for it is not search but knowing, and we seek confirmation only. Let me tell you that so you will know what we four know already. He, our enemy, have gone away; he have gone back to his Castle in Transylvania. He have prepare for this in some way, and that last earth-box was ready to ship somewheres. For this he took the money; for this he hurry at the last, lest we catch him before the sun go down.",
                "He is clever, oh, so clever! He know that his game here was finish; and so he decide he go back home. He find ship going by the route he came, and he go in it. We go off now to find what ship, and whither bound; when we have discover that, we come back and tell you all. Then we will comfort you and poor dear Madam Mina with new hope.",
                "This battle is but begun, and in the end we shall win -- so sure as that God sits on high to watch over His children. Therefore be of much comfort till we return.",
            ],
            "signoff": "-- Your friend,",
            "signature": "VAN HELSING.",
        },
    ],
    "plates": [
        {
            "after_doc": 1,
            "file": "plates/trance.jpg",
            "numeral": "Plate I.",
            "title": "THE TRANCE.",
            "caption": "Her voice had a sad dreaminess which was new to me.",
            "prompt": "19th century oil painting, vertical portrait composition: a lamplit Victorian bedroom just before dawn, a pale young woman sitting up in bed with closed eyes and a far-away expression, a white-bearded old professor making slow passes with his hands before her face, her anxious husband watching from the foot of the bed, rosy dawn light at the edge of a window blind. Deeply atmospheric, Victorian book-illustration style. No text, no watermark.",
        },
        {
            "after_doc": 4,
            "file": "plates/czarina.jpg",
            "numeral": "Plate II.",
            "title": "THE CZARINA CATHERINE.",
            "caption": "A thin mist began to creep up from the river, till soon a dense fog enveloped the ship and all around her.",
            "prompt": "19th century oil painting, vertical portrait composition: a tall-masted sailing barque enveloped in dense unnatural fog at a grimy London wharf at dusk, gas-lamps glowing dimly through the mist, a tall thin figure in black wearing a straw hat standing at the top of the gang-plank, crates and a great wooden box on the quay. Ominous and atmospheric, Victorian book-illustration style. No text, no watermark.",
        },
        {
            "after_doc": 5,
            "file": "plates/routes.jpg",
            "numeral": "Plate III.",
            "title": "THE TWO ROADS TO VARNA.",
            "caption": "To sail a ship takes time; when we start we go on land more quick, and we meet him there.",
            "prompt": "Antique hand-drawn map, 1890s cartographic style, sepia ink on aged parchment: map of Europe showing a dotted sea route from London down the Channel and round to the Dardanelles and the Black Sea to Varna, and a second dashed overland rail route from London across the continent to Varna, with small ship and train vignettes, ornate compass rose. Text labels are allowed on this map.",
        },
    ],
}
