# -*- coding: latin-1 -*-
CHAPTER = {
    "number": 8,
    "label": "CHAPTER EIGHT",
    "title": "MINA MURRAY'S JOURNAL",
    "subtitle": "11th -- 19th August -- Whitby",
    "epigraph": '"I shall be patient, Master. It is coming -- coming -- coming!"',
    "docs": [
        {
            "num": "No. I.",
            "title": "THE SLEEP-WALKER.",
            "subtitle": "From Mina Murray's Journal, 11th August, 3 a. m.",
            "style": "prose",
            "paras": [
                "We have had such an adventure, such an agonising experience. I fell asleep as soon as I had closed my diary. Suddenly I became broad awake, and sat up, with a horrible sense of fear upon me, and of some feeling of emptiness around me. The room was dark, so I could not see Lucy's bed; I stole across and felt for her. The bed was empty. The door was shut, but not locked, as I had left it.",
                "As I was leaving the room it struck me that the clothes she wore might give me some clue to her dreaming intention. Dressing-gown would mean house; dress, outside. Dressing-gown and dress were both in their places. \"Thank God,\" I said to myself, \"she cannot be far, as she is only in her nightdress.\" I ran downstairs and looked in the sitting-room. Not there! Then I looked in all the other open rooms of the house, with an ever-growing fear chilling my heart. Finally I came to the hall door and found it open. It was not wide open, but the catch of the lock had not caught.",
                "There was no time to think of what might happen; a vague, overmastering fear obscured all details. I took a big, heavy shawl and ran out. The clock was striking one as I was in the Crescent, and there was not a soul in sight. At the edge of the West Cliff above the pier I looked across the harbour to the East Cliff, in the hope or fear -- I don't know which -- of seeing Lucy in our favourite seat.",
                "There was a bright full moon, with heavy black, driving clouds, which threw the whole scene into a fleeting diorama of light and shade as they sailed across. Then as the cloud passed I could see the ruins of the abbey coming into view; and as the edge of a narrow band of light as sharp as a sword-cut moved along, the church and the churchyard became gradually visible. Whatever my expectation was, it was not disappointed, for there, on our favourite seat, the silver light of the moon struck a half-reclining figure, snowy white. But it seemed to me as though something dark stood behind the seat where the white figure shone, and bent over it. What it was, whether man or beast, I could not tell.",
                "I did not wait to catch another glance, but flew down the steep steps to the pier and along by the fish-market to the bridge, which was the only way to reach the East Cliff. When I got almost to the top I could see the seat and the white figure, for I was now close enough to distinguish it even through the spells of shadow. There was undoubtedly something, long and black, bending over the half-reclining white figure. I called in fright, \"Lucy! Lucy!\" and something raised a head, and from where I was I could see a white face and red, gleaming eyes.",
                "As I entered, the church was between me and the seat, and for a minute or so I lost sight of her. When I came in view again the cloud had passed, and the moonlight struck so brilliantly that I could see Lucy half reclining with her head lying over the back of the seat. She was quite alone, and there was not a sign of any living thing about.",
                "When I bent over her I could see that she was still asleep. Her lips were parted, and she was breathing -- not softly as usual with her, but in long, heavy gasps, as though striving to get her lungs full at every breath. As I came close, she put up her hand in her sleep and pulled the collar of her nightdress close around her throat.",
                "I flung the warm shawl over her, and drew the edges tight round her neck, for I dreaded lest she should get some deadly chill from the night air, unclad as she was. I feared to wake her all at once, so, in order to have my hands free that I might help her, I fastened the shawl at her throat with a big safety-pin; but I must have been clumsy in my anxiety and pinched or pricked her with it, for by-and-by, when her breathing became quieter, she put her hand to her throat again and moaned.",
                "Fortune favoured us, and we got home without meeting a soul. When we got in, and had washed our feet, and had said a prayer of thankfulness together, I tucked her into bed. Before falling asleep she asked -- even implored -- me not to say a word to any one, even her mother, about her sleep-walking adventure. I thought it wiser to promise. I have locked the door, and the key is tied to my wrist, so perhaps I shall not be again disturbed.",
            ],
        },
        {
            "num": "No. II.",
            "title": "THE TWO LITTLE WOUNDS.",
            "subtitle": "From Mina Murray's Journal, 11th -- 14th August.",
            "style": "prose",
            "paras": [
                "I was sorry to notice that my clumsiness with the safety-pin hurt her. Indeed, it might have been serious, for the skin of her throat was pierced. I must have pinched up a piece of loose skin and have transfixed it, for there are two little red points like pin-pricks, and on the band of her nightdress was a drop of blood. When I apologised and was concerned about it, she laughed and petted me, and said she did not even feel it. Fortunately it cannot leave a scar, as it is so tiny.",
                "On the 13th I awoke in the night, and found Lucy sitting up in bed, still asleep, pointing to the window. I got up quietly, and pulling aside the blind, looked out. It was brilliant moonlight. Between me and the moonlight flitted a great bat, coming and going in great whirling circles. Once or twice it came quite close, but was, I suppose, frightened at seeing me, and flitted away across the harbour towards the abbey. When I came back from the window Lucy had lain down again, and was sleeping peacefully.",
                "On the 14th, coming home for dinner, we stopped at the top of the steps up from the West Pier to look at the view, as we generally do. The setting sun was just dropping behind Kettleness; the red light was thrown over on the East Cliff and the old abbey, and seemed to bathe everything in a beautiful rosy glow. We were silent for a while, and suddenly Lucy murmured as if to herself: \"His red eyes again! They are just the same.\"",
                "It was such an odd expression, coming apropos of nothing, that it quite startled me. She appeared to be looking over at our own seat, whereon was a dark figure seated alone. I was a little startled myself, for it seemed for an instant as if the stranger had great eyes like burning flames; but a second look dispelled the illusion. The red sunlight was shining on the windows of St. Mary's Church behind our seat, and as the sun dipped there was just sufficient change in the refraction and reflection to make it appear as if the light moved. I called Lucy's attention to the peculiar effect, and she became herself with a start, but she looked sad all the same.",
                "When coming home -- it was then bright moonlight -- I threw a glance up at our window, and saw Lucy's head leaning out. I opened my handkerchief and waved it. She did not notice or make any movement whatever. Just then, the moonlight crept round an angle of the building, and the light fell on the window. There distinctly was Lucy with her head lying up against the side of the window-sill and her eyes shut. She was fast asleep, and by her, seated on the window-sill, was something that looked like a good-sized bird.",
                "I ran upstairs, but as I came into the room she was moving back to her bed, fast asleep, and breathing heavily; she was holding her hand to her throat, as though to protect it from cold. I did not wake her, but tucked her up warmly. She looks so sweet as she sleeps; but she is paler than is her wont, and there is a drawn, haggard look under her eyes which I do not like.",
            ],
        },
        {
            "num": "No. III.",
            "title": "SISTER AGATHA'S LETTER.",
            "subtitle": "Hospital of St. Joseph and Ste. Mary, Buda-Pesth, to Miss Wilhelmina Murray.",
            "style": "letter",
            "opening": [
                "12th August, 1893.",
                "Dear Madam, --",
            ],
            "paras": [
                "I write by desire of Mr. Jonathan Harker, who is himself not strong enough to write, though progressing well, thanks to God and St. Joseph and Ste. Mary. He has been under our care for nearly six weeks, suffering from a violent brain fever. He wishes me to convey his love, and to say that by this post I write for him to Mr. Peter Hawkins, Exeter, to say, with his dutiful respects, that he is sorry for his delay, and that all of his work is completed.",
                "He will require some few weeks' rest in our sanatorium in the hills, but will then return. He wishes me to say that he has not sufficient money with him, and that he would like to pay for his staying here, so that others who need shall not be wanting for help.",
                "P. S. -- My patient being asleep, I open this to let you know something more. He has told me all about you, and that you are shortly to be his wife. All blessings to you both! He has had some fearful shock -- so says our doctor -- and in his delirium his ravings have been dreadful; of wolves and poison and blood; of ghosts and demons; and I fear to say of what. Be careful with him always that there may be nothing to excite him of this kind for a long time to come; the traces of such an illness as his do not lightly die away.",
                "We should have written long ago, but we knew nothing of his friends, and there was on him nothing that any one could understand. He came in the train from Klausenburg, and the guard was told by the station-master there that he rushed into the station shouting for a ticket for home. Be assured that he is well cared for. He has won all hearts by his sweetness and gentleness.",
            ],
            "signoff": "Believe me,",
            "signature": "SISTER AGATHA.",
        },
        {
            "num": "No. IV.",
            "title": "THE BOXES OF EARTH.",
            "subtitle": "Samuel F. Billington & Son, Solicitors, Whitby, to Messrs. Carter, Paterson & Co., London.",
            "style": "letter",
            "opening": [
                "17th August, 1893.",
                "Dear Sirs, --",
            ],
            "paras": [
                "Herewith please receive invoice of goods sent by Great Northern Railway. Same are to be delivered at Carfax, near Purfleet, immediately on receipt at goods station King's Cross. The house is at present empty, but enclosed please find keys, all of which are labelled.",
                "You will please deposit the boxes, fifty in number, which form the consignment, in the partially ruined building forming part of the house and marked \"A\" on rough diagram enclosed. Your agent will easily recognise the locality, as it is the ancient chapel of the mansion. The goods leave by the train at 9:30 to-night, and will be due at King's Cross at 4:30 to-morrow afternoon. As our client wishes the delivery made as soon as possible, we shall be obliged by your having teams ready at King's Cross at the time named and forthwith conveying the goods to destination.",
                "In order to obviate any delays possible through any routine requirements as to payment in your departments, we enclose cheque herewith for ten pounds (10 pounds), receipt of which please acknowledge. Should the charge be less than this amount, you can return balance; if greater, we shall at once send cheque for difference on hearing from you. You are to leave the keys on coming away in the main hall of the house, where the proprietor may get them on his entering the house by means of his duplicate key.",
                "Pray do not take us as exceeding the bounds of business courtesy in pressing you in all ways to use the utmost expedition.",
            ],
            "signoff": "We are, dear Sirs,",
            "signature": "SAMUEL F. BILLINGTON & SON.",
        },
        {
            "num": "No. V.",
            "title": "THE CARRIERS' REPLY.",
            "subtitle": "Messrs. Carter, Paterson & Co., London, to Messrs. Billington & Son, Whitby.",
            "style": "letter",
            "opening": [
                "21st August, 1893.",
                "Dear Sirs, --",
            ],
            "paras": [
                "We beg to acknowledge 10 pounds received and to return cheque 1 pound 17s. 9d., amount of overplus, as shown in receipted account herewith. Goods are delivered in exact accordance with instructions, and keys left in parcel in main hall, as directed.",
            ],
            "signoff": "We are, dear Sirs,",
            "signature": "Pro CARTER, PATERSON & CO.",
        },
        {
            "num": "No. VI.",
            "title": "THE MASTER IS AT HAND.",
            "subtitle": "From Dr. Seward's Diary, 19th August.",
            "style": "prose",
            "paras": [
                "Strange and sudden change in Renfield last night. About eight o'clock he began to get excited and sniff about as a dog does when setting. The attendant was struck by his manner, and knowing my interest in him, encouraged him to talk. All he would say was: \"I don't want to talk to you: you don't count now; the Master is at hand.\" The attendant thinks it is some sudden form of religious mania which has seized him.",
                "At nine o'clock I visited him myself. His attitude to me was the same as that to the attendant. It looks like religious mania, and he will soon think that he himself is God. For half an hour or more Renfield kept getting excited in greater and greater degree. All at once that shifty look came into his eyes which we always see when a madman has seized an idea. He became quite quiet, and went and sat on the edge of his bed resignedly.",
                "I thought I would find out if his apathy were real or only assumed, and tried to lead him to talk of his pets, a theme which had never failed to excite his attention. At first he made no reply, but at length said testily: \"Bother them all! I don't care a pin about them.\" \"What?\" I said. \"You don't mean to tell me you don't care about spiders?\" To this he answered enigmatically: \"The bride-maidens rejoice the eyes that wait the coming of the bride; but when the bride draweth nigh, then the maidens shine not to the eyes that are filled.\"",
                "Later. -- Glad I made the resolution to take no chloral; gladder that I kept to it. I had lain tossing about, and had heard the clock strike only twice, when the night-watchman came to me to say that Renfield had escaped. His attention was called by the sound of the window being wrenched out. He ran back and saw his feet disappear through the window. He was only in his night-gear, and cannot be far off.",
                "I am thin, so, with the attendant's aid, I got out through the window, feet foremost, and landed unhurt. As I got through the belt of trees I saw a white figure scale the high wall which separates our grounds from those of the deserted house. I got a ladder myself, and crossing the wall, dropped down on the other side. I could see Renfield's figure just disappearing behind the angle of the house, so I ran after him.",
                "On the far side of the house I found him pressed close against the old ironbound oak door of the chapel. He was talking, apparently to some one. Chasing an errant swarm of bees is nothing to following a naked lunatic, when the fit of escaping is upon him! After a few minutes I ventured to draw nearer, and heard him say: \"I am here to do Your bidding, Master. I am Your slave, and You will reward me, for I shall be faithful. I have worshipped You long and afar off. Now that You are near, I await Your commands, and You will not pass me by, will You, dear Master, in Your distribution of good things?\"",
                "When we closed in on him he fought like a tiger. He is immensely strong, for he was more like a wild beast than a man. He is safe now at any rate. Jack Sheppard himself couldn't get free from the strait-waistcoat that keeps him restrained, and he's chained to the wall in the padded room. His cries are at times awful, but the silences that follow are more deadly still, for he means murder in every turn and movement.",
                "Just now he spoke coherent words for the first time: \"I shall be patient, Master. It is coming -- coming -- coming!\" So I took the hint, and came too. I was too excited to sleep, but this diary has quieted me, and I feel I shall get some sleep to-night.",
            ],
        },
    ],
    "plates": [
        {
            "after_doc": 0,
            "file": "plates/empty-seat.jpg",
            "numeral": "Plate I.",
            "title": "THE EMPTY SEAT.",
            "caption": "The favourite seat among the tombstones, found vacant in the moonlight; only a discarded shawl left behind.",
            "prompt": "19th century oil painting, vertical portrait composition: a moonlit churchyard on a clifftop at night, an empty stone bench among leaning tombstones with a discarded shawl draped over it, ruined Gothic abbey behind, full moon and driving black clouds, no people. Deeply atmospheric, Victorian book-illustration style. No text, no watermark.",
        },
        {
            "after_doc": 3,
            "file": "plates/boxes.jpg",
            "numeral": "Plate II.",
            "title": "THE FIFTY BOXES.",
            "caption": "Deposited by the carriers in the ancient chapel of Carfax, near Purfleet, as instructed.",
            "prompt": "19th century oil painting, vertical portrait composition: a ruined ancient stone chapel interior at night lit by lanterns, workmen unloading great wooden crates from a horse-drawn wagon outside, stacks of large earth-filled boxes piled in the ruined nave, mist curling through broken arches. Deeply atmospheric, Victorian book-illustration style. No text, no watermark.",
        },
        {
            "after_doc": 5,
            "file": "plates/renfield-chapel.jpg",
            "numeral": "Plate III.",
            "title": "THE ESCAPE.",
            "caption": "Pressed close against the old ironbound oak door of the chapel: \"I am here to do Your bidding, Master.\"",
            "prompt": "19th century oil painting, vertical portrait composition: a gaunt wild-eyed man in nightclothes pressed close against a massive ironbound oak door of an old chapel at night, hands raised in supplication, moonlight through trees, distant asylum attendants with a lantern approaching through a walled garden. Deeply atmospheric, Victorian book-illustration style. No text, no watermark.",
        },
    ],
}
