# -*- coding: latin-1 -*-
"""Chapter 26 content for the Dracula companion."""
CHAPTER = {
    "number": 26,
    "label": "CHAPTER TWENTY-SIX",
    "title": "DR. SEWARD'S DIARY",
    "subtitle": "29th October -- 4th November",
    "epigraph": '"Something is going out; I can feel it pass me like a cold wind."',
    "docs": [
        {
            "num": "No. I.",
            "title": "TELEGRAM.",
            "subtitle": "Lord Godalming to the ship's agents.",
            "style": "telegram",
            "tfrom": "Lord Godalming, Varna",
            "tto": "Messrs. Mackenzie and Steinkoff, Galatz",
            "tdated": "29th October",
            "body": "Arrive Galatz to-morrow morning STOP Show us every civility in your power STOP We desire to search ship Czarina Catherine upon arrival STOP Authority from owners follows STOP Godalming STOP",
        },
        {
            "num": "No. II.",
            "title": "THE AGENTS AT GALATZ.",
            "subtitle": "From Mr. Harker's journal, 30th October.",
            "style": "prose",
            "paras": [
                "At nine o'clock Dr. Van Helsing, Dr. Seward, and I called on Messrs. Mackenzie and Steinkoff, the agents of the London firm of Hapgood. They had received a wire from London, in answer to Lord Godalming's telegraphed request, asking us to show them any civility in their power. They took us at once on board the Czarina Catherine, which lay at anchor out in the river harbour. There we saw the Captain, Donelson by name, who told us of his voyage.",
                "'It\'s no canny to run frae London to the Black Sea wi\' a wind ahint ye, as though the Deil himself were blawin\' on yer sail for his ain purpose. An\' a\' the time we could no speer a thing. Gin we were nigh a ship, or a port, or a headland, a fog fell on us and travelled wi\' us.' When they got past the Bosphorus the men began to grumble; some of them, the Roumanians, came and asked him to heave overboard a big box which had been put on board by a queer looking old man just before they had started from London. 'I had to argy wi\' them aboot it wi\' a handspike.'",
                "In the morning, an hour before sun-up, a man came aboard with an order to receive a box marked for one Count Dracula. He had his papers all right, and glad the Captain was to be rid of the thing. 'What was the name of the man who took it?' asked Dr. Van Helsing with restrained eagerness. The Captain produced a receipt signed 'Immanuel Hildesheim.' Burgen-strasse 16 was the address.",
                "We found Hildesheim in his office, a Hebrew of rather the Adelphi Theatre type, with a nose like a sheep, and a fez. His arguments were pointed with specie -- we doing the punctuation -- and with a little bargaining he told us what he knew. He had received a letter from Mr. de Ville of London, telling him to receive, if possible before sunrise so as to avoid customs, a box which would arrive at Galatz in the Czarina Catherine. This he was to give in charge to a certain Petrof Skinsky, who dealt with the Slovaks who traded down the river to the port.",
                "We then sought for Skinsky, but were unable to find him. Whilst we were talking one came running and breathlessly gasped out that the body of Skinsky had been found inside the wall of the churchyard of St. Peter, and that the throat had been torn open as if by some wild animal.",
            ],
        },
        {
            "num": "No. III.",
            "title": "MURDER IN ST. PETER'S CHURCHYARD.",
            "subtitle": "Galatz, 30th October.",
            "style": "notice",
            "lead": "THE BODY OF PETROF SKINSKY HAS BEEN FOUND.",
            "paras": [
                "Inside the wall of the churchyard of St. Peter, the throat torn open as if by some wild animal.",
                'Those we had been speaking with ran off to see the horror, the women crying out "This is the work of a Slovak!"',
                "We hurried away lest we should have been in some way drawn into the affair, and so detained.",
            ],
        },
        {
            "num": "No. IV.",
            "title": "THE STEAM LAUNCH.",
            "subtitle": "Charter for the pursuit up the river.",
            "style": "bill",
            "bill_title": "CHARTER OF A STEAM LAUNCH.",
            "bill_sub": "Taken by Lord Godalming, 30th October, for the pursuit up the river.",
            "items": [
                ("Hire of a steam launch, with steam up, ready at a moment's notice", "--"),
                ("Coal for the furnaces, day and night", "--"),
                ("Repairs after forcing the rapids, by an amateur fitter", "--"),
                ("A Roumanian flag, procured at Fundu", "--"),
                ("Provisions for the chase", "--"),
            ],
            "total": "TOTAL ............ charged to the wonderful power of money.",
            "note": "(Lord Godalming is an experienced hand at the work, as he has had for years a launch of his own on the Thames, and another on the Norfolk Broads. What can money not do when it is properly applied!)",
        },
        {
            "num": "No. V.",
            "title": "MRS. HARKER'S MEMORANDUM.",
            "subtitle": "Ground of inquiry: how the Count is to get back to his own place.",
            "style": "prose",
            "paras": [
                "He must be brought back by some one. This is evident; for had he power to move himself as he wished he could go either as man, or wolf, or bat, or in some other way. He evidently fears discovery or interference, in the state of helplessness in which he must be -- confined as he is between dawn and sunset in his wooden box.",
                "By road there are endless difficulties, especially in leaving the city. There are people; and people are curious, and investigate. A hint, a surmise, a doubt as to what might be in the box, would destroy him. There are, or there may be, customs and octroi officers to pass. His pursuers might follow.",
                "By rail there is no one in charge of the box. It would have to take its chance of being delayed; and delay would be fatal, with enemies on the track. True, he might escape at night; but what would he be, if left in a strange place with no refuge that he could fly to?",
                "By water is the safest way, in one respect, but with most danger in another. On the water he is powerless except at night; even then he can only summon fog and storm and snow and his wolves. But were he wrecked, the living water would engulf him, helpless; and he would indeed be lost.",
                "I have examined the map and find that the river most suitable for the Slovaks to have ascended is either the Pruth or the Sereth. I read in the typescript that in my trance I heard cattle low and water swirling level with my ears and the creaking of wood. The Count in his box, then, was on a river in an open boat -- propelled probably either by oars or poles, for the banks are near and it is working against stream.",
                "Of course it may not be either the Sereth or the Pruth, but we may possibly investigate further. Now of these two, the Pruth is the more easily navigated, but the Sereth is, at Fundu, joined by the Bistritza which runs up round the Borgo Pass. The loop it makes is manifestly as close to Dracula's castle as can be got by water.",
            ],
        },
        {
            "num": "No. VI.",
            "title": "ORDERS FOR THE PURSUIT.",
            "subtitle": "Agreed in council of war, 30th October.",
            "style": "notice",
            "lead": "NOW MEN, TO OUR COUNCIL OF WAR.",
            "paras": [
                "Lord Godalming and Mr. Harker go in the swift little steamboat up the river.",
                "Dr. Seward and Mr. Morris guard the bank on horseback, lest by chance he land; half a dozen good horses, well appointed. There must be force to overcome force if need be; the Slovak is strong and rough, and he carries rude arms.",
                "Professor Van Helsing and Mrs. Harker take the 11:40 train to-night for Veresti, and thence by carriage over the Borgo Pass -- right into the heart of the enemy's country.",
                '"Do as you will," said Jonathan, with a sob that shook him all over, "we are in the hands of God!"',
            ],
        },
        {
            "num": "No. VII.",
            "title": "OUTFIT AT VERESTI.",
            "subtitle": "Purchases of Dr. Van Helsing, 31st October.",
            "style": "bill",
            "bill_title": "VERESTI.",
            "bill_sub": "Purchases of Dr. Van Helsing, 31st October.",
            "items": [
                ("A carriage, and horses to draw it", "--"),
                ("Additional horses, to change upon the way", "--"),
                ("Fur coats and wraps, and all sorts of warm things", "--"),
                ("A basket of provisions, enough for a company of soldiers", "--"),
                ("One large-bore revolver, for the lady", "--"),
            ],
            "total": "TOTAL ............ paid in ready money.",
            "note": "(We have something more than 70 miles before us, and there are snow-flurries which come and go as warnings. We shall drive ourselves, for we have no one whom we can trust in the matter.)",
        },
    ],
    "plates": [
        {
            "after_doc": 1,
            "file": "plates/hildesheim.jpg",
            "numeral": "Plate I.",
            "title": "THE RECEIPT.",
            "caption": "A receipt signed 'Immanuel Hildesheim' -- the box handed over an hour before sun-up.",
            "prompt": "19th century oil painting, vertical portrait composition: a bearded sea captain on the deck of a sailing barque at dawn handing a signed receipt to a dapper mustached man in a fez, a great wooden box on the deck between them, Roumanian dockworkers and a wide river harbour beyond. Deeply atmospheric, Victorian book-illustration style. No text, no watermark.",
        },
        {
            "after_doc": 3,
            "file": "plates/launch.jpg",
            "numeral": "Plate II.",
            "title": "THE STEAM LAUNCH.",
            "caption": "Rushing along through the darkness, with the cold from the river seeming to rise up and strike us.",
            "prompt": "19th century oil painting, vertical portrait composition: a small steam launch rushing up a wide dark river at night, the furnace door glowing orange with a man stoking it while another steers, black Carpathian hills on either bank, first snow falling. Deeply atmospheric, Victorian book-illustration style. No text, no watermark.",
        },
        {
            "after_doc": 4,
            "file": "plates/map.jpg",
            "numeral": "Plate III.",
            "title": "THE RIVERS.",
            "caption": "The Sereth, at Fundu, is joined by the Bistritza, which runs up round the Borgo Pass.",
            "prompt": "Antique hand-drawn map, 1890s cartographic style, sepia ink on aged parchment: the rivers Sereth, Pruth and Bistritza winding through the Carpathians, the Borgo Pass and Castle Dracula marked, dotted lines showing the box's route by water and the overland route by carriage, small compass rose. Text labels are fine. No watermark.",
        },
    ],
}
