# -*- coding: latin-1 -*-
"""Chapter 19 content for the Dracula companion.

1 -- 2 Oct. Harker's journal: the 5 a.m. search of Carfax -- arms,
skeleton keys, dust, the chapel, 29 of 50 boxes, the face in the
passage, rats and terriers; Van Helsing's visit to Renfield
("old fool Van Helsing"); Mina's journal -- kept in the dark, the
mist dream, the sleeping draught.
"""
CHAPTER = {
    "number": 19,
    "label": "CHAPTER NINETEEN",
    "title": "JONATHAN HARKER'S JOURNAL",
    "subtitle": "1st -- 2nd October -- Carfax",
    "epigraph": '"There were only twenty-nine left out of the fifty!"',
    "docs": [
        {
            "num": "No. I.",
            "title": "THE ENTERING OF CARFAX.",
            "subtitle": "From Mr. Harker's journal, 1st October, 5 a.m.; the party goes to the Count's house.",
            "style": "prose",
            "paras": [
                "I went with the party to the search with an easy mind, for I think I never saw Mina so absolutely strong and well. I am so glad that she consented to hold back and let us men do the work.",
                "When we got to the porch the Professor opened his bag and took out a lot of things, which he laid on the step, sorting them into four little groups, evidently one for each. Then he spoke: \"My friends, we are going into a terrible danger, and we need arms of many kinds. Our enemy is not merely spiritual. Remember that he has the strength of twenty men.\"",
                "\"Keep this near your heart\" -- as he spoke he lifted a little silver crucifix and held it out to me -- \"put these flowers round your neck\" -- here he handed to me a wreath of withered garlic blossoms -- \"for other enemies more mundane, this revolver and this knife; and for aid in all, these so small electric lamps, which you can fasten to your breast; and for all, and above all at the last, this, which we must not desecrate needless.\" This was a portion of Sacred Wafer, which he put in an envelope and handed to me. Each of the others was similarly equipped.",
                "Dr. Seward tried one or two skeleton keys, his mechanical dexterity as a surgeon standing him in good stead. Presently he got one to suit; after a little play back and forward the bolt yielded, and, with a rusty clang, shot back. The Professor was the first to move forward, and stepped into the open door. \"In manus tuas, Domine!\" he said, crossing himself as he passed over the threshold.",
                "The whole place was thick with dust. The floor was seemingly inches deep, except where there were recent footsteps, in which on holding down my lamp I could see marks of hobnails where the dust was cracked. On a table in the hall was a great bunch of keys, with a time-yellowed label on each. \"You know this place, Jonathan,\" said the Professor. \"You have copied maps of it, and you know it at least more than we do. Which is the way to the chapel?\"",
                "I had an idea of its direction, though on my former visit I had not been able to get admission to it; so I led the way, and after a few wrong turnings found myself opposite a low, arched oaken door, ribbed with iron bands.",
            ],
        },
        {
            "num": "No. II.",
            "title": "ACCOUNT OF THE EARTH-BOXES.",
            "subtitle": "Taken in the chapel at Carfax, 1st October, before dawn.",
            "style": "bill",
            "bill_title": "CARFAX, PURFLEET.",
            "bill_sub": "Account of the earth-boxes, examined 1st October.",
            "items": [
                ("Landed at Carfax from Whitby, in all", "50"),
                ("Found remaining in the chapel", "29"),
                ("Removed, destination unknown", "21"),
                ("Air of the chapel", "corruption become itself corrupt"),
                ("Rats, in thousands", "put to flight by three terriers"),
            ],
            "total": "BALANCE ............ 21 boxes to be traced.",
            "note": "(A glance was sufficient to show how many remained, for the great earth chests were bulky, and there was no mistaking them. The dust had been much disturbed where the missing boxes had been brought out through the great iron-bound oaken door.)",
        },
        {
            "num": "No. III.",
            "title": "THE FACE IN THE PASSAGE.",
            "subtitle": "What Mr. Harker fancied he saw; what Lord Godalming said of it.",
            "style": "prose",
            "paras": [
                "Once I got a fright, for, seeing Lord Godalming suddenly turn and look out of the vaulted door into the dark passage beyond, I looked too, and for an instant my heart stood still. Somewhere, looking out from the shadow, I seemed to see the high lights of the Count's evil face, the ridge of the nose, the red eyes, the red lips, the awful pallor.",
                "It was only for a moment, for, as Lord Godalming said, \"I thought I saw a face, but it was only the shadows,\" and resumed his inquiry. I turned my lamp in the direction, and stepped into the passage. There was no sign of any one; and as there were no corners, no doors, no aperture of any kind, but only the solid walls of the passage, there could be no hiding-place even for him. I took it that fear had helped imagination, and said nothing.",
                "A few minutes later I saw Morris step suddenly back from a corner, which he was examining. We all followed his movements with our eyes, for undoubtedly some nervousness was growing on us, and we saw a whole mass of phosphorescence, which twinkled like stars. We all instinctively drew back. The whole place was becoming alive with rats.",
                "For a moment or two we stood appalled, all save Lord Godalming, who was seemingly prepared for such an emergency. Rushing over to the great iron-bound oaken door, he turned the key in the lock, drew the huge bolts, and swung the door open. Then, taking his little silver whistle from his pocket, he blew a low, shrill call. It was answered from behind Dr. Seward's house by the yelping of dogs, and after about a minute three terriers came dashing round the corner of the house.",
                "The dogs dashed on, but at the threshold suddenly stopped and snarled, and then, simultaneously lifting their noses, began to howl in most lugubrious fashion. The rats were multiplying in thousands, and we moved out. Lord Godalming lifted one of the dogs, and carrying him in, placed him on the floor. The instant his feet touched the ground he seemed to recover his courage, and rushed at his natural enemies. They fled before him so fast that before he had shaken the life out of a score, the other dogs, who had by now been lifted in the same manner, had but small prey ere the whole mass had vanished.",
            ],
        },
        {
            "num": "No. IV.",
            "title": "RESOLUTION.",
            "subtitle": "Agreed by the party upon their return from Carfax, before dawn.",
            "style": "notice",
            "lead": "SHE IS TO BE LEFT OUT OF OUR FUTURE WORK.",
            "paras": [
                "More than all do I rejoice that this, our first -- and perhaps our most difficult and dangerous -- step has been accomplished without the bringing thereinto our most sweet Madam Mina, or troubling her waking or sleeping thoughts with sights and sounds and smells of horror which she might never forget.",
                "One lesson, too, we have learned, if it be allowable to argue a particulari: that the brute beasts which are to the Count's command are yet themselves not amenable to his spiritual power; for look, these rats that would come to his call, just as from his castle top he summon the wolves, though they come to him, they run pell-mell from the so little dogs of my friend Arthur.",
                "We have other matters before us, other dangers, other fears; and that monster -- he has not used his power over the brute world for the only or the last time to-night. So be it that he has gone elsewhere. Good! It has given us opportunity to cry \"check\" in some ways in this chess game, which we play for the stake of human souls.",
            ],
        },
        {
            "num": "No. V.",
            "title": "THE OLD FOOL VAN HELSING.",
            "subtitle": "From Dr. Seward's diary, 1st October; the Professor visits the patient alone.",
            "style": "prose",
            "paras": [
                "It was towards noon when I was awakened by the Professor walking into my room. He was more jolly and cheerful than usual, and it is quite evident that last night's work has helped to take some of the brooding weight off his mind. \"Your patient interests me much,\" said he. \"May it be that with you I visit him this morning?\" I had some work to do which pressed, so I told him that if he would go alone I would be glad.",
                "Before the Professor left the room I cautioned him against getting any false impression from my patient. \"But,\" he answered, \"I want him to talk of himself and of his delusion as to consuming live things. He said to Madam Mina, as I see in your diary of yesterday, that he had once had such a belief. Why do you smile, friend John?\"",
                "\"Excuse me,\" I said, \"but the answer is here.\" I laid my hand on the type-written matter. \"When our sane and learned lunatic made that very statement of how he used to consume life, his mouth was actually nauseous with the flies and spiders which he had eaten just before Mrs. Harker entered the room.\"",
                "Van Helsing smiled in turn. \"Good!\" he said. \"Your memory is true, friend John. I should have remembered. And yet it is this very obliquity of thought and memory which makes mental disease such a fascinating study.\"",
                "It seemed that the time had been very short indeed, but there was Van Helsing back in the study. \"Do I interrupt?\" he asked politely as he stood at the door. \"Not at all,\" I answered. \"It is needless; I have seen him!\" -- \"Well?\" -- \"I fear that he does not appraise me at much. Our interview was short. When I entered his room he was sitting on a stool in the centre, with his elbows on his knees, and his face was the picture of sullen discontent. I spoke to him as cheerfully as I could, and with such a measure of respect as I could assume. He made no reply whatever. 'Don't you know me?' I asked. His answer was not reassuring: 'I know you well enough; you are the old fool Van Helsing. I wish you would take yourself and your idiotic brain theories somewhere else. Damn all thick-headed Dutchmen!' Not a word more would he say, but sat in his implacable sullenness as indifferent to me as though I had not been in the room at all.\"",
                "Thus departed for this time my chance of much learning from this so clever lunatic; so I shall go, if I may, and cheer myself with a few happy words with that sweet soul Madam Mina. Friend John, it does rejoice me unspeakable that she is no more to be pained, no more to be worried with our terrible things.",
            ],
        },
        {
            "num": "No. VI.",
            "title": "THE PILLAR OF CLOUD.",
            "subtitle": "From Mrs. Harker's journal, 1st October; a dream, set down lest it unseat her reason.",
            "style": "broadside",
            "paras": [
                "Last night I went to bed when the men had gone,",
                "simply because they told me to.",
                "",
                "I lay still and endured; that was all.",
                "The mist grew thicker and thicker",
                "till it seemed as if it became concentrated",
                "into a sort of pillar of cloud in the room,",
                "through the top of which I could see the light of the gas",
                "shining like a red eye.",
                "",
                "The fire divided, and seemed to shine on me through the fog",
                "like two red eyes.",
                "Suddenly the horror burst upon me",
                "that it was thus that Jonathan had seen those awful women",
                "growing into reality through the whirling mist in the moonlight,",
                "and in my dream I must have fainted,",
                "for all became black darkness.",
                "",
                "The last conscious effort which imagination made",
                "was to show me a livid white face",
                "bending over me out of the mist.",
            ],
        },
        {
            "num": "No. VII.",
            "title": "2ND OCTOBER, 10 P.M.",
            "subtitle": "The last lines of Mrs. Harker's journal for the day; a sleeping draught.",
            "style": "prose",
            "paras": [
                "Last night I slept, but did not dream. I must have slept soundly, for I was not waked by Jonathan coming to bed; but the sleep has not refreshed me, for to-day I feel terribly weak and spiritless.",
                "In the afternoon Mr. Renfield asked if he might see me. Poor man, he was very gentle, and when I came away he kissed my hand and bade God bless me. Some way it affected me much; I am crying when I think of him.",
                "After dinner they sent me to bed, and all went off to smoke together, as they said, but I knew that they wanted to tell each other of what had occurred to each during the day. I was not so sleepy as I should have been; so before they went I asked Dr. Seward to give me a little opiate of some kind, as I had not slept well the night before. He very kindly made me up a sleeping draught, which he gave to me, telling me that it would do me no harm, as it was very mild.",
                "I have taken it, and am waiting for sleep, which still keeps aloof. I hope I have not done wrong, for as sleep begins to flirt with me, a new fear comes: that I may have been foolish in thus depriving myself of the power of waking. I might want it. Here comes sleep. Good-night.",
            ],
        },
    ],
    "plates": [
        {
            "after_doc": 1,
            "file": "plates/chapel.jpg",
            "numeral": "Plate I.",
            "title": "THE CHAPEL AT CARFAX.",
            "caption": "Twenty-nine great earth chests stand in the vaulted chapel; the lamps are lit.",
            "prompt": "19th century oil painting, vertical portrait composition: five Victorian gentlemen holding tiny glowing electric lamps examining rows of great wooden earth chests stacked in a dark vaulted stone chapel, thick dust in the lamplight, cobwebs heavy in the corners, one low arched oaken door ribbed with iron. Oppressive and mysterious, Victorian book-illustration style. No text, no watermark.",
        },
        {
            "after_doc": 2,
            "file": "plates/mist.jpg",
            "numeral": "Plate II.",
            "title": "THE MIST.",
            "caption": "The fog pours, not through the window, but through the joinings of the door.",
            "prompt": "19th century oil painting, vertical portrait composition: a sleeping lady in a Victorian bedroom at night while white mist pours under the bedroom door and rises into a tall whirling pillar of cloud, a gas lamp burning like a red eye at the top of the column. Dreamlike and menacing, Victorian book-illustration style. No text, no watermark.",
        },
        {
            "after_doc": 4,
            "file": "plates/lecture.jpg",
            "numeral": "Plate III.",
            "title": "THE PROFESSOR'S LECTURE.",
            "caption": "Van Helsing expounds the vampire's powers -- and its limits -- to the five men.",
            "prompt": "19th century oil painting, vertical portrait composition: a distinguished elderly professor with a white beard lecturing earnestly to five seated listeners in a lamplit Victorian study, gesturing toward notes spread on a great table, faces attentive in the warm lamplight. Scholarly and intense, Victorian book-illustration style. No text, no watermark.",
        },
    ],
}
