# -*- coding: latin-1 -*-
CHAPTER = {
    "number": 7,
    "label": "CHAPTER SEVEN",
    "title": "THE DEMETER",
    "subtitle": "8th -- 10th August -- Whitby",
    "epigraph": '"As idle as a painted ship upon a painted ocean."',
    "docs": [
        {
            "num": "No. I.",
            "title": "A MYSTERIOUS SHIP.",
    "para_after": 7.0,  # nudge the page breaks: keeps a paragraph's first line off the page foot
            "style": "cutting",
            "paper": "The Dailygraph",
            "dateline": "Whitby, 8th August.",
            "headline": "A MYSTERIOUS SHIP.",
            "note": "Pasted in Mina Murray's journal.",
            "paras": [
                "One of the greatest and suddenest storms on record has just been experienced here, with results both strange and unique. The day was unusually fine till the afternoon, when some of the gossips who frequent the East Cliff churchyard called attention to a sudden show of \"mares'-tails\" high in the sky to the north-west. An old fisherman, who for more than half a century has kept watch on weather signs from the East Cliff, foretold in an emphatic manner the coming of a sudden storm.",
                "The only sail noticeable was a foreign schooner with all sails set, which was seemingly going westwards. The foolhardiness or ignorance of her officers was a prolific theme for comment whilst she remained in sight, and efforts were made to signal her to reduce sail in face of her danger. Before the night shut down she was seen with sails idly flapping as she gently rolled on the undulating swell of the sea, \"as idle as a painted ship upon a painted ocean.\"",
                "Then without warning the tempest broke. The waves rose in growing fury, each overtopping its fellow, till in a very few minutes the lately glassy sea was like a roaring and devouring monster. To add to the difficulties and dangers of the time, masses of sea-fog came drifting inland -- white, wet clouds, which swept by in ghostly fashion, so that it needed but little effort of imagination to think that the spirits of those lost at sea were touching their living brethren with the clammy hands of death.",
                "On the summit of the East Cliff the new searchlight was ready for experiment, but had not yet been tried. In the pauses of the inrushing mist the officers swept with it the surface of the sea, and before long discovered some distance away a schooner with all sails set, apparently the same vessel which had been noticed earlier in the evening. There was a shudder amongst the watchers on the cliff as they realized the terrible danger in which she now was, for between her and the port lay the great flat reef on which so many good ships have from time to time suffered.",
                "The wind suddenly shifted to the north-east, and the remnant of the sea-fog melted in the blast; and then, mirabile dictu, between the piers, leaping from wave to wave as it rushed at headlong speed, swept the strange schooner before the blast, with all sail set, and gained the safety of the harbour. The searchlight followed her, and a shudder ran through all who saw her, for lashed to the helm was a corpse, with drooping head, which swung horribly to and fro at each motion of the ship. No other form could be seen on deck at all.",
                "A great awe came on all as they realised that the ship, as if by a miracle, had found the harbour, unsteered save by the hand of a dead man! However, all took place more quickly than it takes to write these words. The schooner paused not, but rushing across the harbour, pitched herself on that accumulation of sand and gravel washed by many tides and many storms into the south-east corner of the pier jutting under the East Cliff, known locally as Tate Hill Pier.",
                "But, strangest of all, the very instant the shore was touched, an immense dog sprang up on deck from below, as if shot up by the concussion, and running forward, jumped from the bow on the sand. Making straight for the steep cliff, where the churchyard hangs over the laneway to the East Pier, it disappeared in the darkness, which seemed intensified just beyond the focus of the searchlight.",
                "The coastguard on duty was the first to climb on board. When he came beside the wheel, bent over to examine it, and recoiled at once as though under some sudden emotion. Your correspondent was, by the courtesy of the chief boatman, permitted to climb on deck, and was one of a small group who saw the dead seaman whilst actually lashed to the wheel. The man was simply fastened by his hands, tied one over the other, to a spoke of the wheel. Between the inner hand and the wood was a crucifix, the set of beads on which it was fastened being around both wrists and wheel, and all kept fast by the binding cords.",
                "Surgeon J. M. Caffyn, of 33, East Elliot Place, declared, after making examination, that the man must have been dead for quite two days. In his pocket was a bottle, carefully corked, empty save for a little roll of paper, which proved to be the addendum to the log. One young law student is loudly asserting that the rights of the owner are already completely sacrificed, his property being held in contravention of the statutes of mortmain, since the tiller, as emblemship, if not proof, of delegated possession, is held in a dead hand. The dead steersman has been reverently removed and placed in the mortuary to await inquest.",
            ],
        },
        {
            "num": "No. II.",
            "title": "THE SEQUEL.",
            "style": "cutting",
            "paper": "The Dailygraph",
            "dateline": "Whitby, 9th August.",
            "headline": "THE SEQUEL.",
            "note": "Pasted in Mina Murray's journal.",
            "paras": [
                "The sequel to the strange arrival of the derelict in the storm last night is almost more startling than the thing itself. It turns out that the schooner is a Russian from Varna, and is called the Demeter. She is almost entirely in ballast of silver sand, with only a small amount of cargo -- a number of great wooden boxes filled with mould. This cargo was consigned to a Whitby solicitor, Mr. S. F. Billington, of 7, The Crescent, who this morning went aboard and formally took possession of the goods consigned to him. The Russian consul, too, acting for the charter-party, took formal possession of the ship, and paid all harbour dues, etc.",
                "A good deal of interest was abroad concerning the dog which landed when the ship struck, and more than a few of the members of the S. P. C. A., which is very strong in Whitby, have tried to befriend the animal. To the general disappointment, however, it was not to be found; it seems to have disappeared entirely from the town. There are some who look with dread on such a possibility, lest later on it should in itself become a danger, for it is evidently a fierce brute.",
                "Early this morning a large dog, a half-bred mastiff belonging to a coal merchant close to Tate Hill Pier, was found dead in the roadway opposite to its master's yard. It had been fighting, and manifestly had had a savage opponent, for its throat was torn away, and its belly was slit open as if with a savage claw.",
                "By the kindness of the Board of Trade inspector, I have been permitted to look over the log-book of the Demeter, which was in order up to within three days, but contained nothing of special interest except as to facts of missing men. The greatest interest, however, is with regard to the paper found in the bottle, which was to-day produced at the inquest; and a more strange narrative than the two between them unfold it has not been my lot to come across. I am permitted to use them, and accordingly send you a rescript, simply omitting technical details of seamanship and supercargo. Of course my statement must be taken cum grano, since I am writing from the dictation of a clerk of the Russian consul, who kindly translated for me, time being short.",
            ],
        },
        {
            "num": "No. III.",
            "title": "LOG OF THE \"DEMETER.\"",
            "subtitle": "Rescript of the log-book, and of the paper found in the bottle; Varna to Whitby.",
            "style": "prose",
            "paras": [
                "Written 18 July, things so strange happening, that I shall keep accurate note henceforth till we land. On 6 July we finished taking in cargo, silver sand and boxes of earth. At noon set sail. East wind, fresh. Crew, five hands ... two mates, cook, and myself (captain). On 11 July at dawn entered Bosphorus. Boarded by Turkish Customs officers. Backsheesh. All correct. Under way at 4 p. m. On 13 July passed Cape Matapan. Crew dissatisfied about something. Seemed scared, but would not speak out. On 14 July the men only told the mate there was something, and crossed themselves. On 16 July mate reported that one of crew, Petrofsky, was missing.",
                "On 17 July, one of the men, Olgaren, confided to me that he thought there was a strange man aboard the ship. He said that in his watch he saw a tall, thin man, who was not like any of the crew, come up the companion-way, and go along the deck forward, and disappear. To allay the panic, I got together the whole crew, and we searched from stem to stern, all keeping abreast, with lanterns: we left no corner unsearched. As there were only the big wooden boxes, there were no odd corners where a man could hide. Men much relieved when search over.",
                "22 July. -- Rough weather last three days, and all hands busy with sails -- no time to be frightened. Passed Gibraltar and out through Straits. All well. 24 July. -- There seems some doom over this ship. Already a hand short, and entering on the Bay of Biscay with wild weather ahead, and yet last night another man lost -- disappeared. 28 July. -- Four days in hell, knocking about in a sort of maelstrom. 29 July. -- Another tragedy. When morning watch came on deck could find no one except steersman. Are now without second mate, and crew in a panic. 30 July. -- Retired worn out; awaked by mate telling me that both man of watch and steersman missing. Only self and mate and two hands left to work ship.",
                "2 August, midnight. -- Woke up by hearing a cry, seemingly outside my port. Rushed on deck, and ran against mate. No sign of man on watch. One more gone. 3 August. -- At midnight I went to relieve the man at the wheel, and when I got to it found no one there. The mate came close to me and whispered hoarsely, with his mouth to my ear: \"It is here; I know it, now. On the watch last night I saw It, like a man, tall and thin, and ghastly pale. It was in the bows, and looking out. I crept behind It, and gave It my knife; but the knife went through It, empty as the air.\" And he went below with a tool-chest and a lantern to unscrew the boxes one by one.",
                "Just as I was beginning to hope that the mate would come out calmer, there came up the hatchway a sudden, startled scream, and up on the deck he came as if shot from a gun -- a raging madman, with his eyes rolling and his face convulsed with fear. \"Save me! save me!\" he cried. \"You had better come too, captain, before it is too late. He is there. I know the secret now. The sea will save me from Him, and it is all that is left!\" Before I could say a word, he sprang on the bulwark and deliberately threw himself into the sea.",
                "4 August. -- Still fog, which the sunrise cannot pierce. I dared not go below, I dared not leave the helm; so here all night I stayed, and in the dimness of the night I saw It -- Him! God forgive me, but the mate was right to jump overboard. But I am captain, and I must not leave my ship. But I shall baffle this fiend or monster, for I shall tie my hands to the wheel when my strength begins to fail, and along with them I shall tie that which He -- It! -- dare not touch; and then, come good wind or foul, I shall save my soul, and my honour as a captain.",
                "Of course the verdict was an open one. There is no evidence to adduce; and whether or not the man himself committed the murders there is now none to say. The folk here hold almost universally that the captain is simply a hero, and he is to be given a public funeral. Already it is arranged that his body is to be taken with a train of boats up the Esk for a piece and then brought back to Tate Hill Pier and up the abbey steps; for he is to be buried in the churchyard on the cliff.",
            ],
        },
        {
            "num": "No. IV.",
            "title": "A PUBLIC FUNERAL.",
            "subtitle": "Whitby, 9th August.",
            "style": "notice",
            "lead": "THE LATE CAPTAIN OF THE DEMETER WILL BE BURIED WITH PUBLIC HONOURS.",
            "paras": [
                "The folk here hold almost universally that the captain is simply a hero, and he is to be given a public funeral. Already it is arranged that his body is to be taken with a train of boats up the Esk for a piece and then brought back to Tate Hill Pier and up the abbey steps; for he is to be buried in the churchyard on the cliff.",
                "The owners of more than a hundred boats have already given in their names as wishing to follow him to the grave. To-morrow will see the funeral; and so will end this one more \"mystery of the sea.\"",
            ],
        },
        {
            "num": "No. V.",
            "title": "AT THE FUNERAL.",
            "subtitle": "From Mina Murray's Journal, 10th August.",
            "style": "prose",
            "paras": [
                "The funeral of the poor sea-captain to-day was most touching. Every boat in the harbour seemed to be there, and the coffin was carried by captains all the way from Tate Hill Pier up to the churchyard. Lucy came with me, and we went early to our old seat, whilst the cortege of boats went up the river to the Viaduct and came down again. We had a lovely view, and saw the procession nearly all the way. The poor fellow was laid to rest quite near our seat so that we stood on it when the time came and saw everything.",
                "Poor Lucy seemed much upset. There is an additional cause in that poor old Mr. Swales was found dead this morning on our seat, his neck being broken. He had evidently, as the doctor said, fallen back in the seat in some sort of fright, for there was a look of fear and horror on his face that the men said made them shudder. Poor dear old man! Perhaps he had seen Death with his dying eyes!",
                "Just now she was quite upset by a little thing which I did not much heed, though I am myself very fond of animals. One of the men who came up here often to look for the boats was followed by his dog. During the service the dog would not come to its master, but kept a few yards off, barking and howling. It was in a sort of fury, with its eyes savage, and all its hairs bristling out like a cat's tail when puss is on the war-path.",
                "Finally the man got angry, and jumped down and kicked the dog, and then took it by the scruff of the neck and half dragged and half threw it on the tombstone on which the seat is fixed. The moment it touched the stone the poor thing became quiet and fell all into a tremble. It did not try to get away, but crouched down, quivering and cowering, and was in such a pitiable state of terror that I tried, though without effect, to comfort it.",
                "I greatly fear that Lucy is of too super-sensitive a nature to go through the world without trouble. The whole agglomeration of things -- the ship steered into port by a dead man; his attitude, tied to the wheel with a crucifix and beads; the touching funeral; the dog, now furious and now in terror -- will all afford material for her dreams.",
            ],
        },
        {
            "num": "No. VI.",
            "title": "MANIFEST OF THE DERELICT.",
            "subtitle": "Taken at Tate Hill Pier, 8th August.",
            "style": "bill",
            "bill_title": "SCHOONER DEMETER, OF VARNA.",
            "bill_sub": "Cargo and effects landed at Whitby, 8th August, 1893.",
            "items": [
                ("Ballast of silver sand", "nil"),
                ("Great wooden boxes, filled with mould, consigned to Mr. S. F. Billington, 7, The Crescent", "delivered"),
                ("One corpse, lashed to the helm, with crucifix and beads", "inquest"),
                ("One immense dog, sprang ashore on touching land", "missing"),
                ("Crew: five hands, two mates, cook, and captain", "unaccounted for"),
            ],
            "total": "TOTAL ............ a mystery of the sea.",
            "note": "(The officials of the Board of Trade have been most exacting in seeing that every compliance has been made with existing regulations. No trace has ever been found of the great dog.)",
        },
    ],
    "plates": [
        {
            "after_doc": 1,
            "file": "plates/grounding.jpg",
            "numeral": "Plate I.",
            "title": "THE DEMETER COMES HOME.",
            "caption": "Unsteered save by the hand of a dead man, she pitches herself upon Tate Hill Pier; the great dog leaps ashore.",
            "prompt": "19th century oil painting, vertical portrait composition: a derelict Russian sailing schooner with all sails set pitching onto a sandbank at a harbour pier at night in a storm, a corpse lashed to the ship's wheel with drooping head, a beam of searchlight cutting through sea-fog, an immense black dog leaping from the bow toward a dark cliff, terrified onlookers on the pier. Deeply atmospheric, Victorian book-illustration style. No text, no watermark.",
        },
        {
            "after_doc": 2,
            "file": "plates/voyage.jpg",
            "numeral": "Plate II.",
            "title": "THE VOYAGE OF THE DEMETER.",
            "caption": "Varna to Whitby, 6th July -- 8th August: the Bosphorus, the Dardanelles, Cape Matapan, Gibraltar, the Bay of Biscay, the Channel.",
            "prompt": "Antique hand-drawn map, 1890s cartographic style, sepia ink on aged parchment: a chart of Europe showing the voyage of a sailing schooner from Varna on the Black Sea through the Bosphorus and Dardanelles, past Cape Matapan, through Gibraltar, across the Bay of Biscay, up the English Channel to Whitby on the Yorkshire coast, with a dotted course line, small date labels, a compass rose and sailing-ship vignettes. Text labels are acceptable on this map. No watermark.",
        },
        {
            "after_doc": 4,
            "file": "plates/funeral.jpg",
            "numeral": "Plate III.",
            "title": "THE CAPTAIN'S FUNERAL.",
            "caption": "The coffin carried by captains up the abbey steps; a train of boats upon the Esk.",
            "prompt": "19th century oil painting, vertical portrait composition: a Victorian funeral procession climbing steep stone steps up a clifftop to a ruined abbey and churchyard, a coffin borne on the shoulders of weathered sea-captains, mourners following, below them a river crowded with small boats in procession, grey Yorkshire sky. Deeply atmospheric, Victorian book-illustration style. No text, no watermark.",
        },
    ],
}
