# -*- coding: latin-1 -*-
CHAPTER = {
    "number": 23,
    "label": "CHAPTER TWENTY-THREE",
    "title": "DR. SEWARD'S DIARY",
    "subtitle": "14th -- 15th October -- the chase begins",
    "epigraph": '"To sail a ship takes time, go she never so quick; and when we start we go on land more quick, and we meet him there."',
    "docs": [
        {
            "num": "No. I.",
            "title": "TELEGRAM.",
            "subtitle": "Lord Godalming opens the correspondence.",
            "style": "telegram",
            "tfrom": "Lord Godalming, London",
            "tto": "Rufus Smith, Lloyd's, London",
            "tdated": "14th October",
            "body": "Kindly report instantly any tidings of barque Czarina Catherine sailed Thames for Varna STOP Request your Dardanelles correspondent wire her passing without fail STOP Matter of the utmost urgency STOP Expenses no object STOP",
        },
        {
            "num": "No. II.",
            "title": "TELEGRAM.",
            "subtitle": "The answer from Lloyd's.",
            "style": "telegram",
            "tfrom": "Rufus Smith, Lloyd's, London",
            "tto": "Lord Godalming, care of H. B. M. Vice-Consul, Varna",
            "tdated": "October",
            "body": "Czarina Catherine reported this morning from Dardanelles STOP",
        },
        {
            "num": "No. III.",
            "title": "TELEGRAM.",
            "subtitle": "To Her Britannic Majesty's representative at Varna.",
            "style": "telegram",
            "tfrom": "Lord Godalming, London",
            "tto": "H. B. M. Vice-Consul, Varna",
            "tdated": "14th October",
            "body": "May I beg your good offices on my arrival STOP A box landed ex Czarina Catherine and consigned to one Ristics may contain property stolen from a friend of mine STOP The ship's owner has given me a paper authorising me to open it at my own risk STOP What is to be done is not for police or of the customs STOP I rely upon your discretion STOP",
        },
        {
            "num": "No. IV.",
            "title": "FROM MINA HARKER'S JOURNAL.",
            "subtitle": "Kept whilst the party waited for tidings of the ship.",
            "style": "prose",
            "paras": [
                "My morning and evening hypnotic answer is unvaried: lapping waves, rushing water, and creaking masts. Darkness, and favouring winds. We are evidently in good time, and when we hear of the Czarina Catherine we shall be ready.",
                "I have asked the Professor why we need seek him further, when he is gone away from us. He took my hand and answered, solemnly: 'Because, my dear, dear Madam Mina, now more than ever must we find him even if we have to follow him to the jaws of Hell!' 'Why?' I asked. 'Because,' he said, 'he can live for centuries, and you are but mortal woman. Time is now to be dreaded -- since once he put that mark upon your throat.'",
                "I am to keep the record as I have done before, and to have all the papers in the safe, and all the papers or diaries and phonographs we may hereafter use. I am pleased with the prospect of anything to do. In trouble and trial our faith is tested; we must keep on trusting, and God will aid us up to the end.",
                "Jonathan has asked me to note this, as he is not quite sure of being able to do so himself: we are all drifting reefwards now, and faith is our only anchor.",
            ],
        },
        {
            "num": "No. V.",
            "title": "THE PLAN OF ATTACK.",
            "subtitle": "Agreed upon, that we may be ready the instant the ship is seen.",
            "style": "prose",
            "paras": [
                "Everything is pretty well fixed now, I think, to welcome the Count on his return from his tour. Godalming told the shippers that he fancied that the box sent aboard might contain something stolen from a friend of his, and got a half consent that he might open it at his own risk. The owner gave him a paper telling the Captain to give him every facility in doing whatever he chose on board the ship, and also a similar authorisation to his agent at Varna.",
                "We have seen the agent, who was much impressed with Godalming's kindly manner to him, and we are all satisfied that whatever he can do to aid our wishes will be done. We have already arranged what to do in case we get the box open. If the Count is there, Van Helsing and Seward will cut off his head at once and drive a stake through his heart. Morris and Godalming and I shall prevent interference, even if we have to use the arms which we shall have ready.",
                "The Professor says that if we can so treat the Count's body, it will soon after fall into dust. In such case there would be no evidence against us, in case any suspicion of murder were aroused. But even if it were not, we should stand or fall by our act, and perhaps some day this very script may be evidence to come between some of us and a rope. For myself, I should take the chance only too thankfully if it were to come.",
                "We have arranged with certain officials that the instant the Czarina Catherine is seen, we are to be informed by a special messenger. We mean to leave no stone unturned to carry out our intent.",
            ],
        },
        {
            "num": "No. VI.",
            "title": "OUTFITTER'S ACCOUNT.",
            "subtitle": "For the expedition; rendered to Lord Godalming.",
            "style": "bill",
            "bill_title": "MESSRS. ----, ARMY & NAVY STORES.",
            "bill_sub": "Supplied per order -- October.",
            "items": [
                ("Five revolvers, .45 calibre, with cases", "12 10 0"),
                ("Cartridges for the same, 500", "2 5 0"),
                ("Great knives, Ghoorka pattern, 2", "1 8 0"),
                ("Sterling silver crucifixes, 6", "3 0 0"),
                ("Pocket compasses, brass, 2", "0 12 0"),
                ("Consecrated wafers, per the Professor's order", "--"),
            ],
            "total": "TOTAL ............ 19 15 0",
            "note": "(The wafers were not in stock, and have been supplied gratis by the Professor from his own stores. Messrs. ---- beg to observe that they do not usually deal in that line.)",
        },
    ],
    "plates": [
        {
            "after_doc": 1,
            "file": "plates/lloyds.jpg",
            "numeral": "Plate I.",
            "title": "NEWS FROM LLOYD'S.",
            "caption": "Czarina Catherine reported this morning from Dardanelles.",
            "prompt": "19th century oil painting, vertical portrait composition: the grand underwriting room at Lloyd's of London in the 1890s, rows of Victorian clerks at tall sloped desks poring over shipping lists and ledgers, a messenger hurrying in with a telegram slip, tall windows, brass and dark wood. Rich period detail, Victorian book-illustration style. No text, no watermark.",
        },
        {
            "after_doc": 3,
            "file": "plates/waiting.jpg",
            "numeral": "Plate II.",
            "title": "WAITING AT VARNA.",
            "caption": "Mina's morning and evening hypnotic answer is unvaried: lapping waves, rushing water, and creaking masts.",
            "prompt": "19th century oil painting, vertical portrait composition: a pale young woman in a high-necked Victorian dress seated with closed eyes in a trance in a hotel room at sunset, a white-bearded old professor leaning toward her with raised hand, through a tall window the Black Sea glittering red-gold under a setting sun. Melancholy and atmospheric, Victorian book-illustration style. No text, no watermark.",
        },
        {
            "after_doc": 4,
            "file": "plates/blacksea.jpg",
            "numeral": "Plate III.",
            "title": "THE BLACK SEA.",
            "caption": "She should therefore arrive some time in the morning; we shall get up at one o'clock, so as to be ready.",
            "prompt": "Antique hand-drawn map, 1890s cartographic style, sepia ink on aged parchment: chart of the Black Sea showing the Dardanelles, Constantinople, Varna, Galatz and the mouths of the Danube, with a dotted course of a sailing barque marked from the Dardanelles to Varna, small sailing-ship vignette and ornate compass rose, sea monsters in the margins. Text labels are allowed on this map.",
        },
    ],
}
